///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Adverse1_Driver_Attorney_Details_Save recording.
    /// </summary>
    [TestModule("36e6b87d-a4b8-49d5-b5b9-31bd4c46a725", ModuleType.Recording, 1)]
    public partial class Adverse1_Driver_Attorney_Details_Save : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Adverse1_Driver_Attorney_Details_Save instance = new Adverse1_Driver_Attorney_Details_Save();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Adverse1_Driver_Attorney_Details_Save()
        {
            AD1_Attorney_FirmName_getValue = "";
            AD1_Attorney_FirstName_getValue = "";
            AD1_Attorney_LastName_getValue = "";
            AD1_Attorney_Address1_getValue = "";
            AD1_Attorney_Address2_getValue = "";
            AD1_Attorney_City_getValue = "";
            AD1_Attorney_State_getValue = "";
            AD1_Attorney_Zip_getValue = "";
            AD1_AD_Email_getValue = "";
            AD1_AD_UseType_getValue = "";
            AD1_AD_PhoneType_getValue = "";
            AD1_AD_Source_getValue = "";
            AD1_AD_PhoneNumber_getValue = "";
            AD1_Attorney_RepDate_getValue = "";
            AD1_AD_EmailUseType_getValue = "";
            AD1_AD_EmailSource_getValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Adverse1_Driver_Attorney_Details_Save Instance
        {
            get { return instance; }
        }

#region Variables

        string _AD1_Attorney_FirmName_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_FirmName_getValue.
        /// </summary>
        [TestVariable("bf1b19f0-4377-4e33-9352-b2ec3cfce70a")]
        public string AD1_Attorney_FirmName_getValue
        {
            get { return _AD1_Attorney_FirmName_getValue; }
            set { _AD1_Attorney_FirmName_getValue = value; }
        }

        string _AD1_Attorney_FirstName_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_FirstName_getValue.
        /// </summary>
        [TestVariable("a9cdc641-3245-4a9b-891e-97c5755a91d5")]
        public string AD1_Attorney_FirstName_getValue
        {
            get { return _AD1_Attorney_FirstName_getValue; }
            set { _AD1_Attorney_FirstName_getValue = value; }
        }

        string _AD1_Attorney_LastName_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_LastName_getValue.
        /// </summary>
        [TestVariable("034ebd01-90bf-4fa7-a75f-63a9add2f3e8")]
        public string AD1_Attorney_LastName_getValue
        {
            get { return _AD1_Attorney_LastName_getValue; }
            set { _AD1_Attorney_LastName_getValue = value; }
        }

        string _AD1_Attorney_Address1_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_Address1_getValue.
        /// </summary>
        [TestVariable("9ff374a7-8817-4641-80c5-7ecaf1532382")]
        public string AD1_Attorney_Address1_getValue
        {
            get { return _AD1_Attorney_Address1_getValue; }
            set { _AD1_Attorney_Address1_getValue = value; }
        }

        string _AD1_Attorney_Address2_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_Address2_getValue.
        /// </summary>
        [TestVariable("7597a7ab-30ed-4686-b5f8-eb9ea5729a38")]
        public string AD1_Attorney_Address2_getValue
        {
            get { return _AD1_Attorney_Address2_getValue; }
            set { _AD1_Attorney_Address2_getValue = value; }
        }

        string _AD1_Attorney_City_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_City_getValue.
        /// </summary>
        [TestVariable("af595d0f-37d2-4a20-a51c-c17a13046312")]
        public string AD1_Attorney_City_getValue
        {
            get { return _AD1_Attorney_City_getValue; }
            set { _AD1_Attorney_City_getValue = value; }
        }

        string _AD1_Attorney_State_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_State_getValue.
        /// </summary>
        [TestVariable("4e44a6c7-af6d-45fe-ad9c-0f8548ed78fa")]
        public string AD1_Attorney_State_getValue
        {
            get { return _AD1_Attorney_State_getValue; }
            set { _AD1_Attorney_State_getValue = value; }
        }

        string _AD1_Attorney_Zip_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_Zip_getValue.
        /// </summary>
        [TestVariable("5094a1c5-e7ef-472f-b674-d5c7353afc9f")]
        public string AD1_Attorney_Zip_getValue
        {
            get { return _AD1_Attorney_Zip_getValue; }
            set { _AD1_Attorney_Zip_getValue = value; }
        }

        string _AD1_AD_Email_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_AD_Email_getValue.
        /// </summary>
        [TestVariable("c56e9be5-ba65-4552-946c-ed124b789ab5")]
        public string AD1_AD_Email_getValue
        {
            get { return _AD1_AD_Email_getValue; }
            set { _AD1_AD_Email_getValue = value; }
        }

        string _AD1_AD_UseType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_AD_UseType_getValue.
        /// </summary>
        [TestVariable("b5816266-bd4a-41b2-9db7-c3376bc1830c")]
        public string AD1_AD_UseType_getValue
        {
            get { return _AD1_AD_UseType_getValue; }
            set { _AD1_AD_UseType_getValue = value; }
        }

        string _AD1_AD_PhoneType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_AD_PhoneType_getValue.
        /// </summary>
        [TestVariable("7e1fbecb-58cd-49a3-acf8-9ec01336bd8c")]
        public string AD1_AD_PhoneType_getValue
        {
            get { return _AD1_AD_PhoneType_getValue; }
            set { _AD1_AD_PhoneType_getValue = value; }
        }

        string _AD1_AD_Source_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_AD_Source_getValue.
        /// </summary>
        [TestVariable("1fd2d584-b670-4913-a91c-f77ac86de856")]
        public string AD1_AD_Source_getValue
        {
            get { return _AD1_AD_Source_getValue; }
            set { _AD1_AD_Source_getValue = value; }
        }

        string _AD1_AD_PhoneNumber_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_AD_PhoneNumber_getValue.
        /// </summary>
        [TestVariable("fe553a6a-e651-4403-9470-eef14a5734d0")]
        public string AD1_AD_PhoneNumber_getValue
        {
            get { return _AD1_AD_PhoneNumber_getValue; }
            set { _AD1_AD_PhoneNumber_getValue = value; }
        }

        string _AD1_Attorney_RepDate_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_Attorney_RepDate_getValue.
        /// </summary>
        [TestVariable("bc1a3312-4570-4c11-9f54-f366298904c5")]
        public string AD1_Attorney_RepDate_getValue
        {
            get { return _AD1_Attorney_RepDate_getValue; }
            set { _AD1_Attorney_RepDate_getValue = value; }
        }

        string _AD1_AD_EmailUseType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_AD_EmailUseType_getValue.
        /// </summary>
        [TestVariable("757dfd87-c304-47ae-8821-3ddd7c1f7d27")]
        public string AD1_AD_EmailUseType_getValue
        {
            get { return _AD1_AD_EmailUseType_getValue; }
            set { _AD1_AD_EmailUseType_getValue = value; }
        }

        string _AD1_AD_EmailSource_getValue;

        /// <summary>
        /// Gets or sets the value of variable AD1_AD_EmailSource_getValue.
        /// </summary>
        [TestVariable("cc328106-82bc-44de-aa4c-8b89dcadd7e9")]
        public string AD1_AD_EmailSource_getValue
        {
            get { return _AD1_AD_EmailSource_getValue; }
            set { _AD1_AD_EmailSource_getValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Save_Button' at 6;8.", repo.ApplicationUnderTest.Save_ButtonInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Save_Button.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_FirmName' and assigning its value to variable 'AD1_Attorney_FirmName_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_FirmNameInfo, new RecordItemIndex(2));
            AD1_Attorney_FirmName_getValue = repo.ApplicationUnderTest.AD1_Attorney_FirmName.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_FirmName_getValue, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_FirmName_getValue) on item 'ApplicationUnderTest.AD1_Attorney_FirmName'.", repo.ApplicationUnderTest.AD1_Attorney_FirmNameInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_FirmNameInfo, "TagValue", AD1_Attorney_FirmName_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_FirstName' and assigning its value to variable 'AD1_Attorney_FirstName_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_FirstNameInfo, new RecordItemIndex(5));
            AD1_Attorney_FirstName_getValue = repo.ApplicationUnderTest.AD1_Attorney_FirstName.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_FirstName_getValue, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_FirstName_getValue) on item 'ApplicationUnderTest.AD1_Attorney_FirstName'.", repo.ApplicationUnderTest.AD1_Attorney_FirstNameInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_FirstNameInfo, "TagValue", AD1_Attorney_FirstName_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_LastName' and assigning its value to variable 'AD1_Attorney_LastName_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_LastNameInfo, new RecordItemIndex(8));
            AD1_Attorney_LastName_getValue = repo.ApplicationUnderTest.AD1_Attorney_LastName.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_LastName_getValue, new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_LastName_getValue) on item 'ApplicationUnderTest.AD1_Attorney_LastName'.", repo.ApplicationUnderTest.AD1_Attorney_LastNameInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_LastNameInfo, "TagValue", AD1_Attorney_LastName_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_Address1' and assigning its value to variable 'AD1_Attorney_Address1_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_Address1Info, new RecordItemIndex(11));
            AD1_Attorney_Address1_getValue = repo.ApplicationUnderTest.AD1_Attorney_Address1.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_Address1_getValue, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_Address1_getValue) on item 'ApplicationUnderTest.AD1_Attorney_Address1'.", repo.ApplicationUnderTest.AD1_Attorney_Address1Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_Address1Info, "TagValue", AD1_Attorney_Address1_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_Address2' and assigning its value to variable 'AD1_Attorney_Address2_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_Address2Info, new RecordItemIndex(14));
            AD1_Attorney_Address2_getValue = repo.ApplicationUnderTest.AD1_Attorney_Address2.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_Address2_getValue, new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_Address2_getValue) on item 'ApplicationUnderTest.AD1_Attorney_Address2'.", repo.ApplicationUnderTest.AD1_Attorney_Address2Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_Address2Info, "TagValue", AD1_Attorney_Address2_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_City' and assigning its value to variable 'AD1_Attorney_City_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_CityInfo, new RecordItemIndex(17));
            AD1_Attorney_City_getValue = repo.ApplicationUnderTest.AD1_Attorney_City.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_City_getValue, new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_City_getValue) on item 'ApplicationUnderTest.AD1_Attorney_City'.", repo.ApplicationUnderTest.AD1_Attorney_CityInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_CityInfo, "TagValue", AD1_Attorney_City_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_State' and assigning its value to variable 'AD1_Attorney_State_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_StateInfo, new RecordItemIndex(20));
            AD1_Attorney_State_getValue = repo.ApplicationUnderTest.AD1_Attorney_State.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_State_getValue, new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_State_getValue) on item 'ApplicationUnderTest.AD1_Attorney_State'.", repo.ApplicationUnderTest.AD1_Attorney_StateInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_StateInfo, "TagValue", AD1_Attorney_State_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_Zip' and assigning its value to variable 'AD1_Attorney_Zip_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_ZipInfo, new RecordItemIndex(23));
            AD1_Attorney_Zip_getValue = repo.ApplicationUnderTest.AD1_Attorney_Zip.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_Zip_getValue, new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_Zip_getValue) on item 'ApplicationUnderTest.AD1_Attorney_Zip'.", repo.ApplicationUnderTest.AD1_Attorney_ZipInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_ZipInfo, "TagValue", AD1_Attorney_Zip_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_AD_Email' and assigning its value to variable 'AD1_AD_Email_getValue'.", repo.ApplicationUnderTest.AD1_AD_EmailInfo, new RecordItemIndex(26));
            AD1_AD_Email_getValue = repo.ApplicationUnderTest.AD1_AD_Email.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_AD_Email_getValue, new RecordItemIndex(27));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_AD_Email_getValue) on item 'ApplicationUnderTest.AD1_AD_Email'.", repo.ApplicationUnderTest.AD1_AD_EmailInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_AD_EmailInfo, "TagValue", AD1_AD_Email_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_Attorney_RepDate' and assigning its value to variable 'AD1_Attorney_RepDate_getValue'.", repo.ApplicationUnderTest.AD1_Attorney_RepDateInfo, new RecordItemIndex(29));
            AD1_Attorney_RepDate_getValue = repo.ApplicationUnderTest.AD1_Attorney_RepDate.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_Attorney_RepDate_getValue, new RecordItemIndex(30));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_Attorney_RepDate_getValue) on item 'ApplicationUnderTest.AD1_Attorney_RepDate'.", repo.ApplicationUnderTest.AD1_Attorney_RepDateInfo, new RecordItemIndex(31));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_Attorney_RepDateInfo, "TagValue", AD1_Attorney_RepDate_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_AD_UseType' and assigning its value to variable 'AD1_AD_UseType_getValue'.", repo.ApplicationUnderTest.AD1_AD_UseTypeInfo, new RecordItemIndex(32));
            AD1_AD_UseType_getValue = repo.ApplicationUnderTest.AD1_AD_UseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_AD_UseType_getValue, new RecordItemIndex(33));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_AD_UseType_getValue) on item 'ApplicationUnderTest.AD1_AD_UseType'.", repo.ApplicationUnderTest.AD1_AD_UseTypeInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_AD_UseTypeInfo, "TagValue", AD1_AD_UseType_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_AD_PhoneType' and assigning its value to variable 'AD1_AD_PhoneType_getValue'.", repo.ApplicationUnderTest.AD1_AD_PhoneTypeInfo, new RecordItemIndex(35));
            AD1_AD_PhoneType_getValue = repo.ApplicationUnderTest.AD1_AD_PhoneType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_AD_PhoneType_getValue, new RecordItemIndex(36));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_AD_PhoneType_getValue) on item 'ApplicationUnderTest.AD1_AD_PhoneType'.", repo.ApplicationUnderTest.AD1_AD_PhoneTypeInfo, new RecordItemIndex(37));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_AD_PhoneTypeInfo, "TagValue", AD1_AD_PhoneType_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_AD_Source' and assigning its value to variable 'AD1_AD_Source_getValue'.", repo.ApplicationUnderTest.AD1_AD_SourceInfo, new RecordItemIndex(38));
            AD1_AD_Source_getValue = repo.ApplicationUnderTest.AD1_AD_Source.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_AD_Source_getValue, new RecordItemIndex(39));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_AD_Source_getValue) on item 'ApplicationUnderTest.AD1_AD_Source'.", repo.ApplicationUnderTest.AD1_AD_SourceInfo, new RecordItemIndex(40));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_AD_SourceInfo, "TagValue", AD1_AD_Source_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_AD_PhoneNumber' and assigning its value to variable 'AD1_AD_PhoneNumber_getValue'.", repo.ApplicationUnderTest.AD1_AD_PhoneNumberInfo, new RecordItemIndex(41));
            AD1_AD_PhoneNumber_getValue = repo.ApplicationUnderTest.AD1_AD_PhoneNumber.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_AD_PhoneNumber_getValue, new RecordItemIndex(42));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_AD_PhoneNumber_getValue) on item 'ApplicationUnderTest.AD1_AD_PhoneNumber'.", repo.ApplicationUnderTest.AD1_AD_PhoneNumberInfo, new RecordItemIndex(43));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_AD_PhoneNumberInfo, "TagValue", AD1_AD_PhoneNumber_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_AD_EmailUseType' and assigning its value to variable 'AD1_AD_EmailUseType_getValue'.", repo.ApplicationUnderTest.AD1_AD_EmailUseTypeInfo, new RecordItemIndex(44));
            AD1_AD_EmailUseType_getValue = repo.ApplicationUnderTest.AD1_AD_EmailUseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_AD_EmailUseType_getValue, new RecordItemIndex(45));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_AD_EmailUseType_getValue) on item 'ApplicationUnderTest.AD1_AD_EmailUseType'.", repo.ApplicationUnderTest.AD1_AD_EmailUseTypeInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_AD_EmailUseTypeInfo, "TagValue", AD1_AD_EmailUseType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_AD_EmailSource' and assigning its value to variable 'AD1_AD_EmailSource_getValue'.", repo.ApplicationUnderTest.AD1_AD_EmailSourceInfo, new RecordItemIndex(47));
            AD1_AD_EmailSource_getValue = repo.ApplicationUnderTest.AD1_AD_EmailSource.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_AD_EmailSource_getValue, new RecordItemIndex(48));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_AD_EmailSource_getValue) on item 'ApplicationUnderTest.AD1_AD_EmailSource'.", repo.ApplicationUnderTest.AD1_AD_EmailSourceInfo, new RecordItemIndex(49));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_AD_EmailSourceInfo, "TagValue", AD1_AD_EmailSource_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD1_AD_Email' and assigning its value to variable 'AD1_AD_Email_getValue'.", repo.ApplicationUnderTest.AD1_AD_EmailInfo, new RecordItemIndex(50));
            AD1_AD_Email_getValue = repo.ApplicationUnderTest.AD1_AD_Email.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_AD_Email_getValue, new RecordItemIndex(51));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD1_AD_Email_getValue) on item 'ApplicationUnderTest.AD1_AD_Email'.", repo.ApplicationUnderTest.AD1_AD_EmailInfo, new RecordItemIndex(52));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD1_AD_EmailInfo, "TagValue", AD1_AD_Email_getValue);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(53));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton1' at 46;15.", repo.ApplicationUnderTest.SubmitButton1Info, new RecordItemIndex(54));
            repo.ApplicationUnderTest.SubmitButton1.Click("46;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
