///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Edit_Adverse_Other_Personal_Info recording.
    /// </summary>
    [TestModule("d23864ac-c6fb-4aac-bd8f-2f35ee745b1a", ModuleType.Recording, 1)]
    public partial class Edit_Adverse_Other_Personal_Info : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Edit_Adverse_Other_Personal_Info instance = new Edit_Adverse_Other_Personal_Info();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Edit_Adverse_Other_Personal_Info()
        {
            OAT_PI_FirstName = "";
            OAT_PI_LastName = "";
            OAT_PI_POE = "";
            OAT_PI_Address1 = "";
            OAT_PI_Address2 = "";
            OAT_PI_City = "";
            OAT_PI_State = "";
            OAT_PI_Zip = "";
            OAT_PI_UseType = "";
            OAT_PI_PhoneType = "";
            OAT_PI_Source = "";
            OAT_PI_PhoneNumber = "";
            OAT_PI_EmailUseType = "";
            OAT_PI_EmailSource = "";
            OAT_PI_EmailID = "";
            Edit_OAT_PI_FirstName = "Edit_OAT_PI_FirstName";
            Edit_OAT_PI_LastName = "Edit_OAT_PI_LastName";
            Edit_OAT_PI_POE = "Edit_OAT_PI_POE";
            Edit_OAT_PI_Address1 = "Edit_OAT_PI_Address1";
            Edit_OAT_PI_Address2 = "Edit_OAT_PI_Address2";
            Edit_OAT_PI_City = "Edit_OAT_PI_City";
            Edit_OAT_PI_State = "CT";
            Edit_OAT_PI_Zip = "20007";
            Edit_OAT_PI_UseType = "Personal";
            Edit_OAT_PI_PhoneType = "Fax";
            Edit_OAT_PI_Source = "Caller ID";
            Edit_OAT_PI_PhoneNumber = "9600095007";
            Edit_OAT_PI_EmailUseType = "Business";
            Edit_OAT_PI_EmailSource = "Skip Trace";
            Edit_OAT_PI_EmailID = "Editoatpi@gmail.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Edit_Adverse_Other_Personal_Info Instance
        {
            get { return instance; }
        }

#region Variables

        string _OAT_PI_FirstName;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_FirstName.
        /// </summary>
        [TestVariable("8f0dc845-6313-45bf-8322-66521ef7f942")]
        public string OAT_PI_FirstName
        {
            get { return _OAT_PI_FirstName; }
            set { _OAT_PI_FirstName = value; }
        }

        string _OAT_PI_LastName;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_LastName.
        /// </summary>
        [TestVariable("7b59f4c3-5628-4fb2-9977-a3224206e66c")]
        public string OAT_PI_LastName
        {
            get { return _OAT_PI_LastName; }
            set { _OAT_PI_LastName = value; }
        }

        string _OAT_PI_POE;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_POE.
        /// </summary>
        [TestVariable("e025527e-0b08-4101-a0d6-3d813618cab7")]
        public string OAT_PI_POE
        {
            get { return _OAT_PI_POE; }
            set { _OAT_PI_POE = value; }
        }

        string _OAT_PI_Address1;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_Address1.
        /// </summary>
        [TestVariable("ed36186a-be89-4e84-9b84-fff2670cb0b8")]
        public string OAT_PI_Address1
        {
            get { return _OAT_PI_Address1; }
            set { _OAT_PI_Address1 = value; }
        }

        string _OAT_PI_Address2;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_Address2.
        /// </summary>
        [TestVariable("9de5b4cc-79d5-498b-880e-309b5ddd0c38")]
        public string OAT_PI_Address2
        {
            get { return _OAT_PI_Address2; }
            set { _OAT_PI_Address2 = value; }
        }

        string _OAT_PI_City;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_City.
        /// </summary>
        [TestVariable("4bda5b39-0e7e-4c1c-9d7f-39eb0f5cba85")]
        public string OAT_PI_City
        {
            get { return _OAT_PI_City; }
            set { _OAT_PI_City = value; }
        }

        string _OAT_PI_State;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_State.
        /// </summary>
        [TestVariable("8ebfc79a-e293-4ce5-96e8-ea321743d673")]
        public string OAT_PI_State
        {
            get { return _OAT_PI_State; }
            set { _OAT_PI_State = value; }
        }

        string _OAT_PI_Zip;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_Zip.
        /// </summary>
        [TestVariable("127cc676-aa31-4310-9465-fcf254debebe")]
        public string OAT_PI_Zip
        {
            get { return _OAT_PI_Zip; }
            set { _OAT_PI_Zip = value; }
        }

        string _OAT_PI_UseType;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_UseType.
        /// </summary>
        [TestVariable("18290522-8fe1-4ee8-bd14-f4f5565186fb")]
        public string OAT_PI_UseType
        {
            get { return _OAT_PI_UseType; }
            set { _OAT_PI_UseType = value; }
        }

        string _OAT_PI_PhoneType;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_PhoneType.
        /// </summary>
        [TestVariable("87394fc9-2d89-41a1-b132-28768e68448e")]
        public string OAT_PI_PhoneType
        {
            get { return _OAT_PI_PhoneType; }
            set { _OAT_PI_PhoneType = value; }
        }

        string _OAT_PI_Source;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_Source.
        /// </summary>
        [TestVariable("bca908af-7a2f-48ee-b2e4-972669af8ff8")]
        public string OAT_PI_Source
        {
            get { return _OAT_PI_Source; }
            set { _OAT_PI_Source = value; }
        }

        string _OAT_PI_PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_PhoneNumber.
        /// </summary>
        [TestVariable("4f829d11-7efe-4b4b-a494-b89c86f1ae60")]
        public string OAT_PI_PhoneNumber
        {
            get { return _OAT_PI_PhoneNumber; }
            set { _OAT_PI_PhoneNumber = value; }
        }

        string _OAT_PI_EmailUseType;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_EmailUseType.
        /// </summary>
        [TestVariable("5378c4e8-b3f9-4320-94b4-a0d28bc55cf9")]
        public string OAT_PI_EmailUseType
        {
            get { return _OAT_PI_EmailUseType; }
            set { _OAT_PI_EmailUseType = value; }
        }

        string _OAT_PI_EmailSource;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_EmailSource.
        /// </summary>
        [TestVariable("a1f10200-a302-4cb8-b930-8721dd225a2d")]
        public string OAT_PI_EmailSource
        {
            get { return _OAT_PI_EmailSource; }
            set { _OAT_PI_EmailSource = value; }
        }

        string _OAT_PI_EmailID;

        /// <summary>
        /// Gets or sets the value of variable OAT_PI_EmailID.
        /// </summary>
        [TestVariable("411a2926-1bc8-4607-97cc-132adfa0ff9b")]
        public string OAT_PI_EmailID
        {
            get { return _OAT_PI_EmailID; }
            set { _OAT_PI_EmailID = value; }
        }

        string _Edit_OAT_PI_FirstName;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_FirstName.
        /// </summary>
        [TestVariable("ac5b8bb8-5dd7-4eb3-9085-b4201bf4ffd1")]
        public string Edit_OAT_PI_FirstName
        {
            get { return _Edit_OAT_PI_FirstName; }
            set { _Edit_OAT_PI_FirstName = value; }
        }

        string _Edit_OAT_PI_LastName;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_LastName.
        /// </summary>
        [TestVariable("536ce1c2-4b54-4311-9f42-7beb1dbc0d55")]
        public string Edit_OAT_PI_LastName
        {
            get { return _Edit_OAT_PI_LastName; }
            set { _Edit_OAT_PI_LastName = value; }
        }

        string _Edit_OAT_PI_POE;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_POE.
        /// </summary>
        [TestVariable("39d84b6b-7275-4e1b-b514-d2e1aa07317f")]
        public string Edit_OAT_PI_POE
        {
            get { return _Edit_OAT_PI_POE; }
            set { _Edit_OAT_PI_POE = value; }
        }

        string _Edit_OAT_PI_Address1;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_Address1.
        /// </summary>
        [TestVariable("d1871d1c-a51b-402e-85db-3deadd62b19d")]
        public string Edit_OAT_PI_Address1
        {
            get { return _Edit_OAT_PI_Address1; }
            set { _Edit_OAT_PI_Address1 = value; }
        }

        string _Edit_OAT_PI_Address2;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_Address2.
        /// </summary>
        [TestVariable("b45bd2ca-4455-493a-898a-a900e06673ad")]
        public string Edit_OAT_PI_Address2
        {
            get { return _Edit_OAT_PI_Address2; }
            set { _Edit_OAT_PI_Address2 = value; }
        }

        string _Edit_OAT_PI_City;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_City.
        /// </summary>
        [TestVariable("58e4a5e1-461a-444b-a8a0-b3a5bb2059c0")]
        public string Edit_OAT_PI_City
        {
            get { return _Edit_OAT_PI_City; }
            set { _Edit_OAT_PI_City = value; }
        }

        string _Edit_OAT_PI_State;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_State.
        /// </summary>
        [TestVariable("28f808b2-13a1-46de-800a-5022e345ca4a")]
        public string Edit_OAT_PI_State
        {
            get { return _Edit_OAT_PI_State; }
            set { _Edit_OAT_PI_State = value; }
        }

        string _Edit_OAT_PI_Zip;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_Zip.
        /// </summary>
        [TestVariable("f076923b-bfca-4ab7-8415-a53a403e21ca")]
        public string Edit_OAT_PI_Zip
        {
            get { return _Edit_OAT_PI_Zip; }
            set { _Edit_OAT_PI_Zip = value; }
        }

        string _Edit_OAT_PI_UseType;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_UseType.
        /// </summary>
        [TestVariable("c9564466-7af4-4211-b073-7429ec3311d2")]
        public string Edit_OAT_PI_UseType
        {
            get { return _Edit_OAT_PI_UseType; }
            set { _Edit_OAT_PI_UseType = value; }
        }

        string _Edit_OAT_PI_PhoneType;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_PhoneType.
        /// </summary>
        [TestVariable("ce3ed1a3-a84f-498e-b4c8-819ae52cd820")]
        public string Edit_OAT_PI_PhoneType
        {
            get { return _Edit_OAT_PI_PhoneType; }
            set { _Edit_OAT_PI_PhoneType = value; }
        }

        string _Edit_OAT_PI_Source;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_Source.
        /// </summary>
        [TestVariable("c489de3d-7342-4c2b-9a1c-3c36c190c888")]
        public string Edit_OAT_PI_Source
        {
            get { return _Edit_OAT_PI_Source; }
            set { _Edit_OAT_PI_Source = value; }
        }

        string _Edit_OAT_PI_PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_PhoneNumber.
        /// </summary>
        [TestVariable("6bc6a43a-6d21-4297-be1e-89239b2db5d4")]
        public string Edit_OAT_PI_PhoneNumber
        {
            get { return _Edit_OAT_PI_PhoneNumber; }
            set { _Edit_OAT_PI_PhoneNumber = value; }
        }

        string _Edit_OAT_PI_EmailUseType;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_EmailUseType.
        /// </summary>
        [TestVariable("4edd86e0-fd00-489d-ac3c-01338be33768")]
        public string Edit_OAT_PI_EmailUseType
        {
            get { return _Edit_OAT_PI_EmailUseType; }
            set { _Edit_OAT_PI_EmailUseType = value; }
        }

        string _Edit_OAT_PI_EmailSource;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_EmailSource.
        /// </summary>
        [TestVariable("a879773e-c4be-4fe7-bed8-53e89670cf9d")]
        public string Edit_OAT_PI_EmailSource
        {
            get { return _Edit_OAT_PI_EmailSource; }
            set { _Edit_OAT_PI_EmailSource = value; }
        }

        string _Edit_OAT_PI_EmailID;

        /// <summary>
        /// Gets or sets the value of variable Edit_OAT_PI_EmailID.
        /// </summary>
        [TestVariable("a04253c8-e810-40b0-8c83-468907fd7206")]
        public string Edit_OAT_PI_EmailID
        {
            get { return _Edit_OAT_PI_EmailID; }
            set { _Edit_OAT_PI_EmailID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_FirstName) on item 'ApplicationUnderTest.OAT_PI_FirstName'.", repo.ApplicationUnderTest.OAT_PI_FirstNameInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_FirstNameInfo, "TagValue", OAT_PI_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_FirstName, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(3));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(4));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_OAT_PI_FirstName' with focus on 'ApplicationUnderTest.OAT_PI_FirstName'.", repo.ApplicationUnderTest.OAT_PI_FirstNameInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.OAT_PI_FirstName.PressKeys(Edit_OAT_PI_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_LastName) on item 'ApplicationUnderTest.OAT_PI_LastName'.", repo.ApplicationUnderTest.OAT_PI_LastNameInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_LastNameInfo, "TagValue", OAT_PI_LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_LastName, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(8));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(9));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_OAT_PI_LastName' with focus on 'ApplicationUnderTest.OAT_PI_LastName'.", repo.ApplicationUnderTest.OAT_PI_LastNameInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.OAT_PI_LastName.PressKeys(Edit_OAT_PI_LastName);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_POE) on item 'ApplicationUnderTest.OAT_PI_POE'.", repo.ApplicationUnderTest.OAT_PI_POEInfo, new RecordItemIndex(11));
            //Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_POEInfo, "TagValue", OAT_PI_POE);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "User", OAT_PI_POE, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_Address1) on item 'ApplicationUnderTest.OAT_PI_Address1'.", repo.ApplicationUnderTest.OAT_PI_Address1Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Address1Info, "TagValue", OAT_PI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_Address1, new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(15));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(16));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_OAT_PI_Address1' with focus on 'ApplicationUnderTest.OAT_PI_Address1'.", repo.ApplicationUnderTest.OAT_PI_Address1Info, new RecordItemIndex(17));
            repo.ApplicationUnderTest.OAT_PI_Address1.PressKeys(Edit_OAT_PI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_Address2) on item 'ApplicationUnderTest.OAT_PI_Address2'.", repo.ApplicationUnderTest.OAT_PI_Address2Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Address2Info, "TagValue", OAT_PI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_Address2, new RecordItemIndex(19));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(20));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(21));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_OAT_PI_Address2' with focus on 'ApplicationUnderTest.OAT_PI_Address2'.", repo.ApplicationUnderTest.OAT_PI_Address2Info, new RecordItemIndex(22));
            repo.ApplicationUnderTest.OAT_PI_Address2.PressKeys(Edit_OAT_PI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_City) on item 'ApplicationUnderTest.OAT_PI_City'.", repo.ApplicationUnderTest.OAT_PI_CityInfo, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_CityInfo, "TagValue", OAT_PI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_City, new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(25));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(26));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_OAT_PI_City' with focus on 'ApplicationUnderTest.OAT_PI_City'.", repo.ApplicationUnderTest.OAT_PI_CityInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.OAT_PI_City.PressKeys(Edit_OAT_PI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_State) on item 'ApplicationUnderTest.OAT_PI_State'.", repo.ApplicationUnderTest.OAT_PI_StateInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_StateInfo, "TagValue", OAT_PI_State);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_State, new RecordItemIndex(29));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(30));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(31));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_OAT_PI_State' on item 'ApplicationUnderTest.OAT_PI_State'.", repo.ApplicationUnderTest.OAT_PI_StateInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.OAT_PI_State.Element.SetAttributeValue("TagValue", Edit_OAT_PI_State);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_Zip) on item 'ApplicationUnderTest.OAT_PI_Zip'.", repo.ApplicationUnderTest.OAT_PI_ZipInfo, new RecordItemIndex(33));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_ZipInfo, "TagValue", OAT_PI_Zip);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_Zip, new RecordItemIndex(34));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(35));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(36));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_OAT_PI_Zip' with focus on 'ApplicationUnderTest.OAT_PI_Zip'.", repo.ApplicationUnderTest.OAT_PI_ZipInfo, new RecordItemIndex(37));
            repo.ApplicationUnderTest.OAT_PI_Zip.PressKeys(Edit_OAT_PI_Zip);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'ApplicationUnderTest.OAT_PI_Returned_Mail'.", repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, "Checked", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='true') on item 'ApplicationUnderTest.OAT_PI_Returned_Mail'.", repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, new RecordItemIndex(39));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, "Value", "true");
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(40));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_UseType) on item 'ApplicationUnderTest.OAT_PI_UseType'.", repo.ApplicationUnderTest.OAT_PI_UseTypeInfo, new RecordItemIndex(41));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_UseTypeInfo, "TagValue", OAT_PI_UseType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_UseType, new RecordItemIndex(42));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(43));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(44));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_OAT_PI_UseType' on item 'ApplicationUnderTest.OAT_PI_UseType'.", repo.ApplicationUnderTest.OAT_PI_UseTypeInfo, new RecordItemIndex(45));
            repo.ApplicationUnderTest.OAT_PI_UseType.Element.SetAttributeValue("TagValue", Edit_OAT_PI_UseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_PhoneType) on item 'ApplicationUnderTest.OAT_PI_PhoneType'.", repo.ApplicationUnderTest.OAT_PI_PhoneTypeInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_PhoneTypeInfo, "TagValue", OAT_PI_PhoneType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_PhoneType, new RecordItemIndex(47));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(48));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(49));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_OAT_PI_PhoneType' on item 'ApplicationUnderTest.OAT_PI_PhoneType'.", repo.ApplicationUnderTest.OAT_PI_PhoneTypeInfo, new RecordItemIndex(50));
            repo.ApplicationUnderTest.OAT_PI_PhoneType.Element.SetAttributeValue("TagValue", Edit_OAT_PI_PhoneType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_Source) on item 'ApplicationUnderTest.OAT_PI_Source'.", repo.ApplicationUnderTest.OAT_PI_SourceInfo, new RecordItemIndex(51));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_SourceInfo, "TagValue", OAT_PI_Source);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_Source, new RecordItemIndex(52));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+LControlKey' Press.", new RecordItemIndex(53));
            Keyboard.Press(System.Windows.Forms.Keys.LControlKey | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(54));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_OAT_PI_Source' on item 'ApplicationUnderTest.OAT_PI_Source'.", repo.ApplicationUnderTest.OAT_PI_SourceInfo, new RecordItemIndex(55));
            repo.ApplicationUnderTest.OAT_PI_Source.Element.SetAttributeValue("TagValue", Edit_OAT_PI_Source);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.OAT_PI_PhoneNumber' and assigning its value to variable 'OAT_PI_PhoneNumber'.", repo.ApplicationUnderTest.OAT_PI_PhoneNumberInfo, new RecordItemIndex(56));
            OAT_PI_PhoneNumber = repo.ApplicationUnderTest.OAT_PI_PhoneNumber.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_PhoneNumber) on item 'ApplicationUnderTest.OAT_PI_PhoneNumber'.", repo.ApplicationUnderTest.OAT_PI_PhoneNumberInfo, new RecordItemIndex(57));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_PhoneNumberInfo, "TagValue", OAT_PI_PhoneNumber);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_PhoneNumber, new RecordItemIndex(58));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(59));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(60));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_OAT_PI_PhoneNumber'.", new RecordItemIndex(61));
            Keyboard.Press(Edit_OAT_PI_PhoneNumber);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.OAT_PI_EmailUseType' and assigning its value to variable 'OAT_PI_EmailUseType'.", repo.ApplicationUnderTest.OAT_PI_EmailUseTypeInfo, new RecordItemIndex(62));
            OAT_PI_EmailUseType = repo.ApplicationUnderTest.OAT_PI_EmailUseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_EmailUseType, new RecordItemIndex(63));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_EmailUseType) on item 'ApplicationUnderTest.OAT_PI_EmailUseType'.", repo.ApplicationUnderTest.OAT_PI_EmailUseTypeInfo, new RecordItemIndex(64));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_EmailUseTypeInfo, "TagValue", OAT_PI_EmailUseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(65));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(66));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_OAT_PI_EmailUseType' on item 'ApplicationUnderTest.OAT_PI_EmailUseType'.", repo.ApplicationUnderTest.OAT_PI_EmailUseTypeInfo, new RecordItemIndex(67));
            repo.ApplicationUnderTest.OAT_PI_EmailUseType.Element.SetAttributeValue("TagValue", Edit_OAT_PI_EmailUseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.OAT_PI_EmailSource' and assigning its value to variable 'OAT_PI_EmailSource'.", repo.ApplicationUnderTest.OAT_PI_EmailSourceInfo, new RecordItemIndex(68));
            OAT_PI_EmailSource = repo.ApplicationUnderTest.OAT_PI_EmailSource.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_EmailSource, new RecordItemIndex(69));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_EmailSource) on item 'ApplicationUnderTest.OAT_PI_EmailSource'.", repo.ApplicationUnderTest.OAT_PI_EmailSourceInfo, new RecordItemIndex(70));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_EmailSourceInfo, "TagValue", OAT_PI_EmailSource);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(71));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(72));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_OAT_PI_EmailSource' on item 'ApplicationUnderTest.OAT_PI_EmailSource'.", repo.ApplicationUnderTest.OAT_PI_EmailSourceInfo, new RecordItemIndex(73));
            repo.ApplicationUnderTest.OAT_PI_EmailSource.Element.SetAttributeValue("TagValue", Edit_OAT_PI_EmailSource);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.OAT_PI_EmailId' and assigning its value to variable 'OAT_PI_EmailID'.", repo.ApplicationUnderTest.OAT_PI_EmailIdInfo, new RecordItemIndex(74));
            OAT_PI_EmailID = repo.ApplicationUnderTest.OAT_PI_EmailId.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", OAT_PI_EmailID, new RecordItemIndex(75));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$OAT_PI_EmailID) on item 'ApplicationUnderTest.OAT_PI_EmailId'.", repo.ApplicationUnderTest.OAT_PI_EmailIdInfo, new RecordItemIndex(76));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_EmailIdInfo, "TagValue", OAT_PI_EmailID);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(77));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(78));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_OAT_PI_EmailID' with focus on 'ApplicationUnderTest.OAT_PI_EmailId'.", repo.ApplicationUnderTest.OAT_PI_EmailIdInfo, new RecordItemIndex(79));
            repo.ApplicationUnderTest.OAT_PI_EmailId.PressKeys(Edit_OAT_PI_EmailID);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(80));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Save_Button' at 6;8.", repo.ApplicationUnderTest.Save_ButtonInfo, new RecordItemIndex(81));
            repo.ApplicationUnderTest.Save_Button.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_FirstName) on item 'ApplicationUnderTest.OAT_PI_FirstName'.", repo.ApplicationUnderTest.OAT_PI_FirstNameInfo, new RecordItemIndex(82));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_FirstNameInfo, "TagValue", Edit_OAT_PI_FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_FirstName, new RecordItemIndex(83));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_LastName) on item 'ApplicationUnderTest.OAT_PI_LastName'.", repo.ApplicationUnderTest.OAT_PI_LastNameInfo, new RecordItemIndex(84));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_LastNameInfo, "TagValue", Edit_OAT_PI_LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_LastName, new RecordItemIndex(85));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_Address1) on item 'ApplicationUnderTest.OAT_PI_Address1'.", repo.ApplicationUnderTest.OAT_PI_Address1Info, new RecordItemIndex(86));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Address1Info, "TagValue", Edit_OAT_PI_Address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_Address1, new RecordItemIndex(87));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_Address2) on item 'ApplicationUnderTest.OAT_PI_Address2'.", repo.ApplicationUnderTest.OAT_PI_Address2Info, new RecordItemIndex(88));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Address2Info, "TagValue", Edit_OAT_PI_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_Address2, new RecordItemIndex(89));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_City) on item 'ApplicationUnderTest.OAT_PI_City'.", repo.ApplicationUnderTest.OAT_PI_CityInfo, new RecordItemIndex(90));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_CityInfo, "TagValue", Edit_OAT_PI_City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_City, new RecordItemIndex(91));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_State) on item 'ApplicationUnderTest.OAT_PI_State'.", repo.ApplicationUnderTest.OAT_PI_StateInfo, new RecordItemIndex(92));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_StateInfo, "TagValue", Edit_OAT_PI_State);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_State, new RecordItemIndex(93));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_Zip) on item 'ApplicationUnderTest.OAT_PI_Zip'.", repo.ApplicationUnderTest.OAT_PI_ZipInfo, new RecordItemIndex(94));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_ZipInfo, "TagValue", Edit_OAT_PI_Zip);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_Zip, new RecordItemIndex(95));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_UseType) on item 'ApplicationUnderTest.OAT_PI_UseType'.", repo.ApplicationUnderTest.OAT_PI_UseTypeInfo, new RecordItemIndex(96));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_UseTypeInfo, "TagValue", Edit_OAT_PI_UseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_UseType, new RecordItemIndex(97));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_PhoneType) on item 'ApplicationUnderTest.OAT_PI_PhoneType'.", repo.ApplicationUnderTest.OAT_PI_PhoneTypeInfo, new RecordItemIndex(98));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_PhoneTypeInfo, "TagValue", Edit_OAT_PI_PhoneType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_PhoneType, new RecordItemIndex(99));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_Source) on item 'ApplicationUnderTest.OAT_PI_Source'.", repo.ApplicationUnderTest.OAT_PI_SourceInfo, new RecordItemIndex(100));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_SourceInfo, "TagValue", Edit_OAT_PI_Source);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_EmailSource, new RecordItemIndex(101));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_PhoneNumber) on item 'ApplicationUnderTest.OAT_PI_PhoneNumber'.", repo.ApplicationUnderTest.OAT_PI_PhoneNumberInfo, new RecordItemIndex(102));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_PhoneNumberInfo, "TagValue", Edit_OAT_PI_PhoneNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_PhoneNumber, new RecordItemIndex(103));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_EmailUseType) on item 'ApplicationUnderTest.OAT_PI_EmailUseType'.", repo.ApplicationUnderTest.OAT_PI_EmailUseTypeInfo, new RecordItemIndex(104));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_EmailUseTypeInfo, "TagValue", Edit_OAT_PI_EmailUseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_EmailUseType, new RecordItemIndex(105));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_OAT_PI_Source) on item 'ApplicationUnderTest.OAT_PI_EmailSource'.", repo.ApplicationUnderTest.OAT_PI_EmailSourceInfo, new RecordItemIndex(106));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_EmailSourceInfo, "TagValue", Edit_OAT_PI_Source);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_EmailSource, new RecordItemIndex(107));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='yourtext') on item 'ApplicationUnderTest.OAT_PI_EmailId'.", repo.ApplicationUnderTest.OAT_PI_EmailIdInfo, new RecordItemIndex(108));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_EmailIdInfo, "TagValue", "yourtext");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_OAT_PI_EmailID, new RecordItemIndex(109));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton1' at 46;15.", repo.ApplicationUnderTest.SubmitButton1Info, new RecordItemIndex(110));
            repo.ApplicationUnderTest.SubmitButton1.Click("46;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
