///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Edit_Adverse1_Owner_Personal_Information recording.
    /// </summary>
    [TestModule("7893c270-fb7d-4e47-9d3e-1aa3942348c5", ModuleType.Recording, 1)]
    public partial class Edit_Adverse1_Owner_Personal_Information : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Edit_Adverse1_Owner_Personal_Information instance = new Edit_Adverse1_Owner_Personal_Information();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Edit_Adverse1_Owner_Personal_Information()
        {
            AO_PI_FirstName = "";
            AO_PI_LastName = "";
            AO_PI_BusinessName = "";
            AO_PI_Address1 = "";
            AO_PI_Address2 = "";
            AO_PI_City = "";
            AO_PI_USStateCode = "";
            AO_PI_ZipCode = "";
            AO_PI_Email_getValue = "";
            AO_PI_BankruptcyCounty = "";
            AO_PI_BankruptcyDistrict = "";
            AO_PI_BankruptcyChapter = "";
            AO_PI_BankruptcyCaseNo = "";
            AO_PI_PhoneUseType_getValue = "";
            AO_PI_PhoneType_getValue = "";
            AO_PI_PhoneSource_getValue = "";
            AO_PI_PhoneNumber_getValue = "";
            AO_PI_EmailUseType_getValue = "";
            AO_PI_EmailSource_getValue = "";
            AO_PI_EmailID_getValue = "";
            Edit_AO_PI_FirstName = "Edit_AO_PI_FirstName";
            Edit_AO_PI_LastName = "Edit_AO_PI_LastName";
            Edit_AO_PI_BusinessName = "Edit_AO_PI_BusinessName";
            Edit_AO_PI_Address1 = "Edit_AO_PI_Address1";
            Edit_AO_PI_Address2 = "Edit_AO_PI_Address2";
            Edit_AO_PI_City = "Edit_AO_PI_City";
            Edit_AO_PI_USStateCode = "IL";
            Edit_AO_PI_ZipCode = "20003";
            Edit_AO_PI_BankruptcyCounty = "Edit_AO_PI_BankruptcyCounty";
            Edit_AO_PI_BankruptcyDistrict = "Edit_AO_PI_BankruptcyDistrict";
            Edit_AO_PI_BankruptcyChapter = "Edit_AO_PI_BankruptcyChapter";
            Edit_AO_PI_BankruptcyCaseNo = "Edit_AO_PI_BankruptcyCaseNo";
            Edit_AO_PI_PhoneUseType_getValue = "Business";
            Edit_AO_PI_PhoneType_getValue = "Land Line";
            Edit_AO_PI_PhoneSource_getValue = "Direct";
            Edit_AO_PI_PhoneNumber_getValue = "9600095004";
            Edit_AO_PI_EmailUseType_getValue = "Personal";
            Edit_AO_PI_EmailSource_getValue = "Direct";
            Edit_AO_PI_EmailID_getValue = "EditAOPIEmail@gmail.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Edit_Adverse1_Owner_Personal_Information Instance
        {
            get { return instance; }
        }

#region Variables

        string _AO_PI_FirstName;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_FirstName.
        /// </summary>
        [TestVariable("7f73474d-8f81-408b-9454-82370da7e046")]
        public string AO_PI_FirstName
        {
            get { return _AO_PI_FirstName; }
            set { _AO_PI_FirstName = value; }
        }

        string _AO_PI_LastName;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_LastName.
        /// </summary>
        [TestVariable("8277f738-d3f8-45f4-95fe-e0e57eaade35")]
        public string AO_PI_LastName
        {
            get { return _AO_PI_LastName; }
            set { _AO_PI_LastName = value; }
        }

        string _AO_PI_BusinessName;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BusinessName.
        /// </summary>
        [TestVariable("785f05ef-0d88-4599-8b0b-8aa953e00940")]
        public string AO_PI_BusinessName
        {
            get { return _AO_PI_BusinessName; }
            set { _AO_PI_BusinessName = value; }
        }

        string _AO_PI_Address1;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_Address1.
        /// </summary>
        [TestVariable("b59ad8c9-0337-4925-b9ac-5ca8b52bb7dd")]
        public string AO_PI_Address1
        {
            get { return _AO_PI_Address1; }
            set { _AO_PI_Address1 = value; }
        }

        string _AO_PI_Address2;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_Address2.
        /// </summary>
        [TestVariable("5a259f60-eae5-4940-9ebe-25e66dd72455")]
        public string AO_PI_Address2
        {
            get { return _AO_PI_Address2; }
            set { _AO_PI_Address2 = value; }
        }

        string _AO_PI_City;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_City.
        /// </summary>
        [TestVariable("93481dc0-0bc9-44a7-9a82-54bbc748dfe3")]
        public string AO_PI_City
        {
            get { return _AO_PI_City; }
            set { _AO_PI_City = value; }
        }

        string _AO_PI_USStateCode;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_USStateCode.
        /// </summary>
        [TestVariable("656786d2-10c7-44f7-bd03-17bcea05deb0")]
        public string AO_PI_USStateCode
        {
            get { return _AO_PI_USStateCode; }
            set { _AO_PI_USStateCode = value; }
        }

        string _AO_PI_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_ZipCode.
        /// </summary>
        [TestVariable("219cf86d-3ae5-40ae-a456-187b00245cfd")]
        public string AO_PI_ZipCode
        {
            get { return _AO_PI_ZipCode; }
            set { _AO_PI_ZipCode = value; }
        }

        string _AO_PI_Email_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_Email_getValue.
        /// </summary>
        [TestVariable("b4f0f0d9-9670-4afe-8a06-c9783a4a321f")]
        public string AO_PI_Email_getValue
        {
            get { return _AO_PI_Email_getValue; }
            set { _AO_PI_Email_getValue = value; }
        }

        string _AO_PI_BankruptcyCounty;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BankruptcyCounty.
        /// </summary>
        [TestVariable("a5753275-7088-4bc1-920d-2b297220efde")]
        public string AO_PI_BankruptcyCounty
        {
            get { return _AO_PI_BankruptcyCounty; }
            set { _AO_PI_BankruptcyCounty = value; }
        }

        string _AO_PI_BankruptcyDistrict;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BankruptcyDistrict.
        /// </summary>
        [TestVariable("a5665c2f-dfcb-4cd5-a6c5-946eb35a7f1b")]
        public string AO_PI_BankruptcyDistrict
        {
            get { return _AO_PI_BankruptcyDistrict; }
            set { _AO_PI_BankruptcyDistrict = value; }
        }

        string _AO_PI_BankruptcyChapter;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BankruptcyChapter.
        /// </summary>
        [TestVariable("4e061226-94c6-4818-af19-3c040908d43e")]
        public string AO_PI_BankruptcyChapter
        {
            get { return _AO_PI_BankruptcyChapter; }
            set { _AO_PI_BankruptcyChapter = value; }
        }

        string _AO_PI_BankruptcyCaseNo;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BankruptcyCaseNo.
        /// </summary>
        [TestVariable("ffaa357a-29e5-4732-a577-2926c8a5a1c9")]
        public string AO_PI_BankruptcyCaseNo
        {
            get { return _AO_PI_BankruptcyCaseNo; }
            set { _AO_PI_BankruptcyCaseNo = value; }
        }

        string _AO_PI_PhoneUseType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_PhoneUseType_getValue.
        /// </summary>
        [TestVariable("f7315e66-501c-46dd-b643-e8425a93e529")]
        public string AO_PI_PhoneUseType_getValue
        {
            get { return _AO_PI_PhoneUseType_getValue; }
            set { _AO_PI_PhoneUseType_getValue = value; }
        }

        string _AO_PI_PhoneType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_PhoneType_getValue.
        /// </summary>
        [TestVariable("050997e9-da28-464c-a92f-0cde00005c50")]
        public string AO_PI_PhoneType_getValue
        {
            get { return _AO_PI_PhoneType_getValue; }
            set { _AO_PI_PhoneType_getValue = value; }
        }

        string _AO_PI_PhoneSource_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_PhoneSource_getValue.
        /// </summary>
        [TestVariable("722c2ef6-f9e6-43af-a735-ed3eae55200d")]
        public string AO_PI_PhoneSource_getValue
        {
            get { return _AO_PI_PhoneSource_getValue; }
            set { _AO_PI_PhoneSource_getValue = value; }
        }

        string _AO_PI_PhoneNumber_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_PhoneNumber_getValue.
        /// </summary>
        [TestVariable("ddb4ee44-e308-498f-87db-33ded7f3c7a8")]
        public string AO_PI_PhoneNumber_getValue
        {
            get { return _AO_PI_PhoneNumber_getValue; }
            set { _AO_PI_PhoneNumber_getValue = value; }
        }

        string _AO_PI_EmailUseType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_EmailUseType_getValue.
        /// </summary>
        [TestVariable("bd299b03-3c80-4d2e-9489-9ae4ca2aaa89")]
        public string AO_PI_EmailUseType_getValue
        {
            get { return _AO_PI_EmailUseType_getValue; }
            set { _AO_PI_EmailUseType_getValue = value; }
        }

        string _AO_PI_EmailSource_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_EmailSource_getValue.
        /// </summary>
        [TestVariable("e1306cc2-d10d-4323-a468-0503cd03a9ed")]
        public string AO_PI_EmailSource_getValue
        {
            get { return _AO_PI_EmailSource_getValue; }
            set { _AO_PI_EmailSource_getValue = value; }
        }

        string _AO_PI_EmailID_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_EmailID_getValue.
        /// </summary>
        [TestVariable("b397fdff-f1f4-4e02-9eb5-adfb5c202457")]
        public string AO_PI_EmailID_getValue
        {
            get { return _AO_PI_EmailID_getValue; }
            set { _AO_PI_EmailID_getValue = value; }
        }

        string _Edit_AO_PI_FirstName;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_FirstName.
        /// </summary>
        [TestVariable("0074daf2-dcee-4af5-96dd-085c6993c8b0")]
        public string Edit_AO_PI_FirstName
        {
            get { return _Edit_AO_PI_FirstName; }
            set { _Edit_AO_PI_FirstName = value; }
        }

        string _Edit_AO_PI_LastName;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_LastName.
        /// </summary>
        [TestVariable("3f46db0a-7638-424f-9c2a-41567a36d1a5")]
        public string Edit_AO_PI_LastName
        {
            get { return _Edit_AO_PI_LastName; }
            set { _Edit_AO_PI_LastName = value; }
        }

        string _Edit_AO_PI_BusinessName;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_BusinessName.
        /// </summary>
        [TestVariable("56a75aa2-10b4-4a33-97bd-9925dc3d5ba5")]
        public string Edit_AO_PI_BusinessName
        {
            get { return _Edit_AO_PI_BusinessName; }
            set { _Edit_AO_PI_BusinessName = value; }
        }

        string _Edit_AO_PI_Address1;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_Address1.
        /// </summary>
        [TestVariable("9720c9c6-0f22-4545-893e-f8e1a83ee529")]
        public string Edit_AO_PI_Address1
        {
            get { return _Edit_AO_PI_Address1; }
            set { _Edit_AO_PI_Address1 = value; }
        }

        string _Edit_AO_PI_Address2;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_Address2.
        /// </summary>
        [TestVariable("b073baa1-4d7f-4ff2-bd3d-34cf81a67ec4")]
        public string Edit_AO_PI_Address2
        {
            get { return _Edit_AO_PI_Address2; }
            set { _Edit_AO_PI_Address2 = value; }
        }

        string _Edit_AO_PI_City;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_City.
        /// </summary>
        [TestVariable("e80deeb4-63ef-4341-880a-956af862e234")]
        public string Edit_AO_PI_City
        {
            get { return _Edit_AO_PI_City; }
            set { _Edit_AO_PI_City = value; }
        }

        string _Edit_AO_PI_USStateCode;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_USStateCode.
        /// </summary>
        [TestVariable("4e8077cd-4dce-47ce-b509-527938b2184f")]
        public string Edit_AO_PI_USStateCode
        {
            get { return _Edit_AO_PI_USStateCode; }
            set { _Edit_AO_PI_USStateCode = value; }
        }

        string _Edit_AO_PI_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_ZipCode.
        /// </summary>
        [TestVariable("a562df16-112b-4181-92e9-abe874e453c8")]
        public string Edit_AO_PI_ZipCode
        {
            get { return _Edit_AO_PI_ZipCode; }
            set { _Edit_AO_PI_ZipCode = value; }
        }

        string _Edit_AO_PI_BankruptcyCounty;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_BankruptcyCounty.
        /// </summary>
        [TestVariable("c7ba8ce4-2c00-4515-8351-03e56eb6a471")]
        public string Edit_AO_PI_BankruptcyCounty
        {
            get { return _Edit_AO_PI_BankruptcyCounty; }
            set { _Edit_AO_PI_BankruptcyCounty = value; }
        }

        string _Edit_AO_PI_BankruptcyDistrict;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_BankruptcyDistrict.
        /// </summary>
        [TestVariable("709ac5ca-3e3c-4444-b8fb-c825df7c9b9a")]
        public string Edit_AO_PI_BankruptcyDistrict
        {
            get { return _Edit_AO_PI_BankruptcyDistrict; }
            set { _Edit_AO_PI_BankruptcyDistrict = value; }
        }

        string _Edit_AO_PI_BankruptcyChapter;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_BankruptcyChapter.
        /// </summary>
        [TestVariable("b08020b5-92f3-4e56-99b4-435b0d46b79b")]
        public string Edit_AO_PI_BankruptcyChapter
        {
            get { return _Edit_AO_PI_BankruptcyChapter; }
            set { _Edit_AO_PI_BankruptcyChapter = value; }
        }

        string _Edit_AO_PI_BankruptcyCaseNo;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_BankruptcyCaseNo.
        /// </summary>
        [TestVariable("a9e83feb-b7c4-4c60-a0fb-a51675737df9")]
        public string Edit_AO_PI_BankruptcyCaseNo
        {
            get { return _Edit_AO_PI_BankruptcyCaseNo; }
            set { _Edit_AO_PI_BankruptcyCaseNo = value; }
        }

        string _Edit_AO_PI_PhoneUseType_getValue;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_PhoneUseType_getValue.
        /// </summary>
        [TestVariable("90e5e830-7b5a-4f0c-bbc4-3a553cd78d03")]
        public string Edit_AO_PI_PhoneUseType_getValue
        {
            get { return _Edit_AO_PI_PhoneUseType_getValue; }
            set { _Edit_AO_PI_PhoneUseType_getValue = value; }
        }

        string _Edit_AO_PI_PhoneType_getValue;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_PhoneType_getValue.
        /// </summary>
        [TestVariable("0e6e7aa1-748f-4bac-a409-91b92243cc86")]
        public string Edit_AO_PI_PhoneType_getValue
        {
            get { return _Edit_AO_PI_PhoneType_getValue; }
            set { _Edit_AO_PI_PhoneType_getValue = value; }
        }

        string _Edit_AO_PI_PhoneSource_getValue;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_PhoneSource_getValue.
        /// </summary>
        [TestVariable("d58cedfa-9b5f-4fe1-a73e-8c10cdf5222f")]
        public string Edit_AO_PI_PhoneSource_getValue
        {
            get { return _Edit_AO_PI_PhoneSource_getValue; }
            set { _Edit_AO_PI_PhoneSource_getValue = value; }
        }

        string _Edit_AO_PI_PhoneNumber_getValue;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_PhoneNumber_getValue.
        /// </summary>
        [TestVariable("78bdad92-d4c6-4daa-9b8c-1bc4d89e6858")]
        public string Edit_AO_PI_PhoneNumber_getValue
        {
            get { return _Edit_AO_PI_PhoneNumber_getValue; }
            set { _Edit_AO_PI_PhoneNumber_getValue = value; }
        }

        string _Edit_AO_PI_EmailUseType_getValue;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_EmailUseType_getValue.
        /// </summary>
        [TestVariable("9bcb986a-f37e-488d-99c7-8f2538e4bd11")]
        public string Edit_AO_PI_EmailUseType_getValue
        {
            get { return _Edit_AO_PI_EmailUseType_getValue; }
            set { _Edit_AO_PI_EmailUseType_getValue = value; }
        }

        string _Edit_AO_PI_EmailSource_getValue;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_EmailSource_getValue.
        /// </summary>
        [TestVariable("a22ca650-f2b5-498b-b80c-f0e082d41a34")]
        public string Edit_AO_PI_EmailSource_getValue
        {
            get { return _Edit_AO_PI_EmailSource_getValue; }
            set { _Edit_AO_PI_EmailSource_getValue = value; }
        }

        string _Edit_AO_PI_EmailID_getValue;

        /// <summary>
        /// Gets or sets the value of variable Edit_AO_PI_EmailID_getValue.
        /// </summary>
        [TestVariable("f809b204-85ce-4798-a4c6-4dea89168851")]
        public string Edit_AO_PI_EmailID_getValue
        {
            get { return _Edit_AO_PI_EmailID_getValue; }
            set { _Edit_AO_PI_EmailID_getValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_FirstName) on item 'ApplicationUnderTest.AO_PI_FirstName'.", repo.ApplicationUnderTest.AO_PI_FirstNameInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_FirstNameInfo, "TagValue", AO_PI_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_FirstName, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(3));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(4));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_FirstName' with focus on 'ApplicationUnderTest.AO_PI_FirstName'.", repo.ApplicationUnderTest.AO_PI_FirstNameInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.AO_PI_FirstName.PressKeys(Edit_AO_PI_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_LastName) on item 'ApplicationUnderTest.AO_PI_LastName'.", repo.ApplicationUnderTest.AO_PI_LastNameInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_LastNameInfo, "TagValue", AO_PI_LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_LastName, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(8));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(9));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_LastName' with focus on 'ApplicationUnderTest.AO_PI_LastName'.", repo.ApplicationUnderTest.AO_PI_LastNameInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.AO_PI_LastName.PressKeys(Edit_AO_PI_LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BusinessName) on item 'ApplicationUnderTest.AO_PI_BusinessName'.", repo.ApplicationUnderTest.AO_PI_BusinessNameInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BusinessNameInfo, "TagValue", AO_PI_BusinessName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BusinessName, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(13));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(14));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_BusinessName' with focus on 'ApplicationUnderTest.AO_PI_BusinessName'.", repo.ApplicationUnderTest.AO_PI_BusinessNameInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.AO_PI_BusinessName.PressKeys(Edit_AO_PI_BusinessName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_Address1) on item 'ApplicationUnderTest.AO_PI_Address1'.", repo.ApplicationUnderTest.AO_PI_Address1Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_Address1Info, "TagValue", AO_PI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_Address1, new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(18));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(19));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_Address1' with focus on 'ApplicationUnderTest.AO_PI_Address1'.", repo.ApplicationUnderTest.AO_PI_Address1Info, new RecordItemIndex(20));
            repo.ApplicationUnderTest.AO_PI_Address1.PressKeys(Edit_AO_PI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_Address2) on item 'ApplicationUnderTest.AO_PI_Address2'.", repo.ApplicationUnderTest.AO_PI_Address2Info, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_Address2Info, "TagValue", AO_PI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_Address2, new RecordItemIndex(22));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(23));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(24));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_Address2' with focus on 'ApplicationUnderTest.AO_PI_Address2'.", repo.ApplicationUnderTest.AO_PI_Address2Info, new RecordItemIndex(25));
            repo.ApplicationUnderTest.AO_PI_Address2.PressKeys(Edit_AO_PI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_City) on item 'ApplicationUnderTest.AO_PI_City'.", repo.ApplicationUnderTest.AO_PI_CityInfo, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_CityInfo, "TagValue", AO_PI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_City, new RecordItemIndex(27));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(28));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(29));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_City' with focus on 'ApplicationUnderTest.AO_PI_City'.", repo.ApplicationUnderTest.AO_PI_CityInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.AO_PI_City.PressKeys(Edit_AO_PI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_USStateCode) on item 'ApplicationUnderTest.AO_PI_USStateCode'.", repo.ApplicationUnderTest.AO_PI_USStateCodeInfo, new RecordItemIndex(31));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_USStateCodeInfo, "TagValue", AO_PI_USStateCode);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_USStateCode, new RecordItemIndex(32));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(33));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(34));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_USStateCode'.", new RecordItemIndex(35));
            Keyboard.Press(Edit_AO_PI_USStateCode);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_ZipCode' and assigning its value to variable 'AO_PI_ZipCode'.", repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, new RecordItemIndex(36));
            //AO_PI_ZipCode = repo.ApplicationUnderTest.AO_PI_ZipCode.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_ZipCode) on item 'ApplicationUnderTest.AO_PI_ZipCode'.", repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, new RecordItemIndex(37));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, "TagValue", AO_PI_ZipCode);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_ZipCode, new RecordItemIndex(38));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(39));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(40));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_ZipCode' with focus on 'ApplicationUnderTest.AO_PI_ZipCode'.", repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, new RecordItemIndex(41));
            repo.ApplicationUnderTest.AO_PI_ZipCode.PressKeys(Edit_AO_PI_ZipCode);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_Email' and assigning its value to variable 'AO_PI_Email_getValue'.", repo.ApplicationUnderTest.AO_PI_EmailInfo, new RecordItemIndex(42));
            //AO_PI_Email_getValue = repo.ApplicationUnderTest.AO_PI_Email.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "User", AO_PI_Email_getValue, new RecordItemIndex(43));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(44));
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_Email_getValue) on item 'ApplicationUnderTest.AO_PI_Email'.", repo.ApplicationUnderTest.AO_PI_EmailInfo, new RecordItemIndex(45));
            //Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailInfo, "TagValue", AO_PI_Email_getValue);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'ApplicationUnderTest.OAT_PI_Returned_Mail'.", repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, "Checked", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='true') on item 'ApplicationUnderTest.OAT_PI_Returned_Mail'.", repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, new RecordItemIndex(47));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, "Value", "true");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_BankruptcyCounty' and assigning its value to variable 'AO_PI_BankruptcyCounty'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, new RecordItemIndex(48));
            //AO_PI_BankruptcyCounty = repo.ApplicationUnderTest.AO_PI_BankruptcyCounty.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BankruptcyCounty) on item 'ApplicationUnderTest.AO_PI_BankruptcyCounty'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, new RecordItemIndex(49));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, "TagValue", AO_PI_BankruptcyCounty);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BankruptcyCounty, new RecordItemIndex(50));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(51));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(52));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_BankruptcyCounty' with focus on 'ApplicationUnderTest.AO_PI_BankruptcyCounty'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, new RecordItemIndex(53));
            repo.ApplicationUnderTest.AO_PI_BankruptcyCounty.PressKeys(Edit_AO_PI_BankruptcyCounty);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_BankruptcyDistrict' and assigning its value to variable 'AO_PI_BankruptcyDistrict'.", repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, new RecordItemIndex(54));
            //AO_PI_BankruptcyDistrict = repo.ApplicationUnderTest.AO_PI_BankruptcyDistrict.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BankruptcyDistrict) on item 'ApplicationUnderTest.AO_PI_BankruptcyDistrict'.", repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, new RecordItemIndex(55));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, "TagValue", AO_PI_BankruptcyDistrict);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BankruptcyDistrict, new RecordItemIndex(56));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(57));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(58));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_BankruptcyDistrict' with focus on 'ApplicationUnderTest.AO_PI_BankruptcyDistrict'.", repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, new RecordItemIndex(59));
            repo.ApplicationUnderTest.AO_PI_BankruptcyDistrict.PressKeys(Edit_AO_PI_BankruptcyDistrict);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_BankruptcyChapter' and assigning its value to variable 'AO_PI_BankruptcyChapter'.", repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, new RecordItemIndex(60));
            //AO_PI_BankruptcyChapter = repo.ApplicationUnderTest.AO_PI_BankruptcyChapter.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BankruptcyChapter) on item 'ApplicationUnderTest.AO_PI_BankruptcyChapter'.", repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, new RecordItemIndex(61));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, "TagValue", AO_PI_BankruptcyChapter);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BankruptcyChapter, new RecordItemIndex(62));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(63));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(64));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_BankruptcyChapter' with focus on 'ApplicationUnderTest.AO_PI_BankruptcyChapter'.", repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, new RecordItemIndex(65));
            repo.ApplicationUnderTest.AO_PI_BankruptcyChapter.PressKeys(Edit_AO_PI_BankruptcyChapter);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_BankruptcyCaseNo' and assigning its value to variable 'AO_PI_BankruptcyCaseNo'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, new RecordItemIndex(66));
            //AO_PI_BankruptcyCaseNo = repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNo.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BankruptcyCaseNo) on item 'ApplicationUnderTest.AO_PI_BankruptcyCaseNo'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, new RecordItemIndex(67));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, "TagValue", AO_PI_BankruptcyCaseNo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BankruptcyCaseNo, new RecordItemIndex(68));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(69));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(70));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_BankruptcyCaseNo' with focus on 'ApplicationUnderTest.AO_PI_BankruptcyCaseNo'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, new RecordItemIndex(71));
            repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNo.PressKeys(Edit_AO_PI_BankruptcyCaseNo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_PhoneUseType' and assigning its value to variable 'AO_PI_PhoneUseType_getValue'.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(72));
            AO_PI_PhoneUseType_getValue = repo.ApplicationUnderTest.AO_PI_PhoneUseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_PhoneUseType_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneUseType'.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(73));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, "TagValue", AO_PI_PhoneUseType_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_PhoneUseType_getValue, new RecordItemIndex(74));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(75));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(76));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AO_PI_PhoneUseType_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneUseType'.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(77));
            repo.ApplicationUnderTest.AO_PI_PhoneUseType.Element.SetAttributeValue("TagValue", Edit_AO_PI_PhoneUseType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_PhoneType' and assigning its value to variable 'AO_PI_PhoneType_getValue'.", repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, new RecordItemIndex(78));
            AO_PI_PhoneType_getValue = repo.ApplicationUnderTest.AO_PI_PhoneType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_PhoneType_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneType'.", repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, new RecordItemIndex(79));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, "TagValue", AO_PI_PhoneType_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_PhoneType_getValue, new RecordItemIndex(80));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(81));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(82));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AO_PI_PhoneType_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneType'.", repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, new RecordItemIndex(83));
            repo.ApplicationUnderTest.AO_PI_PhoneType.Element.SetAttributeValue("TagValue", Edit_AO_PI_PhoneType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_PhoneSource' and assigning its value to variable 'AO_PI_PhoneSource_getValue'.", repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, new RecordItemIndex(84));
            AO_PI_PhoneSource_getValue = repo.ApplicationUnderTest.AO_PI_PhoneSource.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_PhoneSource_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneSource'.", repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, new RecordItemIndex(85));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, "TagValue", AO_PI_PhoneSource_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_PhoneSource_getValue, new RecordItemIndex(86));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(87));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(88));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AO_PI_PhoneSource_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneSource'.", repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, new RecordItemIndex(89));
            repo.ApplicationUnderTest.AO_PI_PhoneSource.Element.SetAttributeValue("TagValue", Edit_AO_PI_PhoneSource_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_PhoneNumber' and assigning its value to variable 'AO_PI_PhoneNumber_getValue'.", repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, new RecordItemIndex(90));
            AO_PI_PhoneNumber_getValue = repo.ApplicationUnderTest.AO_PI_PhoneNumber.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_PhoneNumber_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneNumber'.", repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, new RecordItemIndex(91));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, "TagValue", AO_PI_PhoneNumber_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_PhoneNumber_getValue, new RecordItemIndex(92));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(93));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(94));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_PhoneNumber_getValue' with focus on 'ApplicationUnderTest.AO_PI_PhoneNumber'.", repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, new RecordItemIndex(95));
            repo.ApplicationUnderTest.AO_PI_PhoneNumber.PressKeys(Edit_AO_PI_PhoneNumber_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_EmailUseType' and assigning its value to variable 'AO_PI_EmailUseType_getValue'.", repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, new RecordItemIndex(96));
            AO_PI_EmailUseType_getValue = repo.ApplicationUnderTest.AO_PI_EmailUseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_EmailUseType_getValue) on item 'ApplicationUnderTest.AO_PI_EmailUseType'.", repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, new RecordItemIndex(97));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, "TagValue", AO_PI_EmailUseType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_FirstName, new RecordItemIndex(98));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(99));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(100));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AO_PI_EmailUseType_getValue' on item 'ApplicationUnderTest.AO_PI_EmailUseType'.", repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, new RecordItemIndex(101));
            repo.ApplicationUnderTest.AO_PI_EmailUseType.Element.SetAttributeValue("TagValue", Edit_AO_PI_EmailUseType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_EmailSource' and assigning its value to variable 'AO_PI_EmailSource_getValue'.", repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, new RecordItemIndex(102));
            AO_PI_EmailSource_getValue = repo.ApplicationUnderTest.AO_PI_EmailSource.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_EmailSource_getValue) on item 'ApplicationUnderTest.AO_PI_EmailSource'.", repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, new RecordItemIndex(103));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, "TagValue", AO_PI_EmailSource_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_EmailSource_getValue, new RecordItemIndex(104));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(105));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(106));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AO_PI_EmailSource_getValue' on item 'ApplicationUnderTest.AO_PI_EmailSource'.", repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, new RecordItemIndex(107));
            repo.ApplicationUnderTest.AO_PI_EmailSource.Element.SetAttributeValue("TagValue", Edit_AO_PI_EmailSource_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_EmailID' and assigning its value to variable 'AO_PI_EmailID_getValue'.", repo.ApplicationUnderTest.AO_PI_EmailIDInfo, new RecordItemIndex(108));
            AO_PI_EmailID_getValue = repo.ApplicationUnderTest.AO_PI_EmailID.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_EmailID_getValue) on item 'ApplicationUnderTest.AO_PI_EmailID'.", repo.ApplicationUnderTest.AO_PI_EmailIDInfo, new RecordItemIndex(109));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailIDInfo, "TagValue", AO_PI_EmailID_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_EmailID_getValue, new RecordItemIndex(110));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(111));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(112));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AO_PI_EmailID_getValue' with focus on 'ApplicationUnderTest.AO_PI_EmailID'.", repo.ApplicationUnderTest.AO_PI_EmailIDInfo, new RecordItemIndex(113));
            repo.ApplicationUnderTest.AO_PI_EmailID.PressKeys(Edit_AO_PI_EmailID_getValue);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$AO_PI_PhoneUseType_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneUseType'.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(114));
            //repo.ApplicationUnderTest.AO_PI_PhoneUseType.Element.SetAttributeValue("TagValue", AO_PI_PhoneUseType_getValue);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$AO_PI_PhoneType_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneType'.", repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, new RecordItemIndex(115));
            //repo.ApplicationUnderTest.AO_PI_PhoneType.Element.SetAttributeValue("TagValue", AO_PI_PhoneType_getValue);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$AO_PI_PhoneSource_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneSource'.", repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, new RecordItemIndex(116));
            //repo.ApplicationUnderTest.AO_PI_PhoneSource.Element.SetAttributeValue("TagValue", AO_PI_PhoneSource_getValue);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AO_PI_PhoneNumber_getValue' with focus on 'ApplicationUnderTest.AO_PI_PhoneNumber'.", repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, new RecordItemIndex(117));
            //repo.ApplicationUnderTest.AO_PI_PhoneNumber.PressKeys(AO_PI_PhoneNumber_getValue);
            //Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(118));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Save_Button' at 6;8.", repo.ApplicationUnderTest.Save_ButtonInfo, new RecordItemIndex(119));
            repo.ApplicationUnderTest.Save_Button.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_FirstName) on item 'ApplicationUnderTest.AO_PI_FirstName'.", repo.ApplicationUnderTest.AO_PI_FirstNameInfo, new RecordItemIndex(120));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_FirstNameInfo, "TagValue", Edit_AO_PI_FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_FirstName, new RecordItemIndex(121));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_LastName) on item 'ApplicationUnderTest.AO_PI_LastName'.", repo.ApplicationUnderTest.AO_PI_LastNameInfo, new RecordItemIndex(122));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_LastNameInfo, "TagValue", Edit_AO_PI_LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_LastName, new RecordItemIndex(123));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_BusinessName) on item 'ApplicationUnderTest.AO_PI_BusinessName'.", repo.ApplicationUnderTest.AO_PI_BusinessNameInfo, new RecordItemIndex(124));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BusinessNameInfo, "TagValue", Edit_AO_PI_BusinessName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_BusinessName, new RecordItemIndex(125));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_Address1) on item 'ApplicationUnderTest.AO_PI_Address1'.", repo.ApplicationUnderTest.AO_PI_Address1Info, new RecordItemIndex(126));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_Address1Info, "TagValue", Edit_AO_PI_Address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_Address1, new RecordItemIndex(127));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_Address2) on item 'ApplicationUnderTest.AO_PI_Address2'.", repo.ApplicationUnderTest.AO_PI_Address2Info, new RecordItemIndex(128));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_Address2Info, "TagValue", Edit_AO_PI_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_Address2, new RecordItemIndex(129));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_City) on item 'ApplicationUnderTest.AO_PI_City'.", repo.ApplicationUnderTest.AO_PI_CityInfo, new RecordItemIndex(130));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_CityInfo, "TagValue", Edit_AO_PI_City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_City, new RecordItemIndex(131));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_USStateCode) on item 'ApplicationUnderTest.AO_PI_USStateCode'.", repo.ApplicationUnderTest.AO_PI_USStateCodeInfo, new RecordItemIndex(132));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_USStateCodeInfo, "TagValue", Edit_AO_PI_USStateCode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_USStateCode, new RecordItemIndex(133));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_ZipCode) on item 'ApplicationUnderTest.AO_PI_ZipCode'.", repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, new RecordItemIndex(134));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, "TagValue", Edit_AO_PI_ZipCode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_ZipCode, new RecordItemIndex(135));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_BankruptcyCounty) on item 'ApplicationUnderTest.AO_PI_BankruptcyCounty'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, new RecordItemIndex(136));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, "TagValue", Edit_AO_PI_BankruptcyCounty);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_BankruptcyCounty, new RecordItemIndex(137));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_BankruptcyDistrict) on item 'ApplicationUnderTest.AO_PI_BankruptcyDistrict'.", repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, new RecordItemIndex(138));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, "TagValue", Edit_AO_PI_BankruptcyDistrict);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_BankruptcyDistrict, new RecordItemIndex(139));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_BankruptcyChapter) on item 'ApplicationUnderTest.AO_PI_BankruptcyChapter'.", repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, new RecordItemIndex(140));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, "TagValue", Edit_AO_PI_BankruptcyChapter);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_BankruptcyChapter, new RecordItemIndex(141));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_BankruptcyCaseNo) on item 'ApplicationUnderTest.AO_PI_BankruptcyCaseNo'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, new RecordItemIndex(142));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, "TagValue", Edit_AO_PI_BankruptcyCaseNo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_BankruptcyCaseNo, new RecordItemIndex(143));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_PhoneUseType_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneUseType'.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(144));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, "TagValue", Edit_AO_PI_PhoneUseType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_PhoneUseType_getValue, new RecordItemIndex(145));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_PhoneType_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneType'.", repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, new RecordItemIndex(146));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, "TagValue", Edit_AO_PI_PhoneType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_PhoneType_getValue, new RecordItemIndex(147));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_PhoneSource_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneSource'.", repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, new RecordItemIndex(148));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, "TagValue", Edit_AO_PI_PhoneSource_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_PhoneSource_getValue, new RecordItemIndex(149));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_PhoneNumber_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneNumber'.", repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, new RecordItemIndex(150));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, "TagValue", Edit_AO_PI_PhoneNumber_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_PhoneNumber_getValue, new RecordItemIndex(151));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_EmailUseType_getValue) on item 'ApplicationUnderTest.AO_PI_EmailUseType'.", repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, new RecordItemIndex(152));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, "TagValue", Edit_AO_PI_EmailUseType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_EmailUseType_getValue, new RecordItemIndex(153));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_EmailSource_getValue) on item 'ApplicationUnderTest.AO_PI_EmailSource'.", repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, new RecordItemIndex(154));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, "TagValue", Edit_AO_PI_EmailSource_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_EmailSource_getValue, new RecordItemIndex(155));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AO_PI_EmailID_getValue) on item 'ApplicationUnderTest.AO_PI_EmailID'.", repo.ApplicationUnderTest.AO_PI_EmailIDInfo, new RecordItemIndex(156));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailIDInfo, "TagValue", Edit_AO_PI_EmailID_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AO_PI_EmailID_getValue, new RecordItemIndex(157));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton1' at 46;15.", repo.ApplicationUnderTest.SubmitButton1Info, new RecordItemIndex(158));
            repo.ApplicationUnderTest.SubmitButton1.Click("46;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
