///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Edit_Adverse2_Driver_Personal_Information recording.
    /// </summary>
    [TestModule("3fb1b73c-8d3b-42a8-bf97-e4fdf28346cd", ModuleType.Recording, 1)]
    public partial class Edit_Adverse2_Driver_Personal_Information : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Edit_Adverse2_Driver_Personal_Information instance = new Edit_Adverse2_Driver_Personal_Information();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Edit_Adverse2_Driver_Personal_Information()
        {
            AD2_PI_FirstName = "";
            AD2_PI_LastName = "";
            AD2_PI_POE = "";
            AD2_PI_Address1 = "";
            AD2_PI_Address2 = "";
            AD2_PI_City = "";
            AD2_PI_State = "";
            AD2_PI_Zip = "";
            AD2_PI_UseType = "";
            AD2_PI_PhoneType = "";
            AD2_PI_Source = "";
            AD2_PI_PhoneNumber = "";
            AD2_PI_EmailUseType = "";
            AD2_PI_EmailSource = "";
            AD2_PI_Email = "";
            Edit_AD2_PI_FirstName = "Edit_AD2_PI_FirstName";
            Edit_AD2_PI_LastName = "Edit_AD2_PI_LastName";
            Edit_AD2_PI_POE = "Edit_AD2_PI_POE";
            Edit_AD2_PI_Address1 = "Edit_AD2_PI_Address1";
            Edit_AD2_PI_Address2 = "Edit_AD2_PI_Address2";
            Edit_AD2_PI_City = "Edit_AD2_PI_City";
            Edit_AD2_PI_State = "VT";
            Edit_AD2_PI_Zip = "20006";
            Edit_AD2_PI_UseType = "Business";
            Edit_AD2_PI_PhoneType = "Work";
            Edit_AD2_PI_Source = "Caller ID";
            Edit_AD2_PI_PhoneNumber = "9600095004";
            Edit_AD2_PI_EmailUseType = "Personal";
            Edit_AD2_PI_EmailSource = "Direct";
            Edit_AD2_PI_Email = "ad2PIemail@gmail.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Edit_Adverse2_Driver_Personal_Information Instance
        {
            get { return instance; }
        }

#region Variables

        string _AD2_PI_FirstName;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_FirstName.
        /// </summary>
        [TestVariable("e6e321b7-83bb-4e0e-b9e5-47d5a0c6d2ce")]
        public string AD2_PI_FirstName
        {
            get { return _AD2_PI_FirstName; }
            set { _AD2_PI_FirstName = value; }
        }

        string _AD2_PI_LastName;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_LastName.
        /// </summary>
        [TestVariable("021d618b-7b0f-4241-bd9a-543725555930")]
        public string AD2_PI_LastName
        {
            get { return _AD2_PI_LastName; }
            set { _AD2_PI_LastName = value; }
        }

        string _AD2_PI_POE;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_POE.
        /// </summary>
        [TestVariable("ceba32f0-1c1f-4846-92c5-d2ac460be6cd")]
        public string AD2_PI_POE
        {
            get { return _AD2_PI_POE; }
            set { _AD2_PI_POE = value; }
        }

        string _AD2_PI_Address1;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_Address1.
        /// </summary>
        [TestVariable("a0e79f8d-c4ff-4462-bacf-c5605b08c0f6")]
        public string AD2_PI_Address1
        {
            get { return _AD2_PI_Address1; }
            set { _AD2_PI_Address1 = value; }
        }

        string _AD2_PI_Address2;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_Address2.
        /// </summary>
        [TestVariable("3f81e661-38d6-4ff0-a3ac-f7e1bbaa51b7")]
        public string AD2_PI_Address2
        {
            get { return _AD2_PI_Address2; }
            set { _AD2_PI_Address2 = value; }
        }

        string _AD2_PI_City;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_City.
        /// </summary>
        [TestVariable("224c56a7-2b45-459e-a85c-9e3a3c2b829a")]
        public string AD2_PI_City
        {
            get { return _AD2_PI_City; }
            set { _AD2_PI_City = value; }
        }

        string _AD2_PI_State;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_State.
        /// </summary>
        [TestVariable("8945126e-47ef-4356-84b1-03f8796fed33")]
        public string AD2_PI_State
        {
            get { return _AD2_PI_State; }
            set { _AD2_PI_State = value; }
        }

        string _AD2_PI_Zip;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_Zip.
        /// </summary>
        [TestVariable("276f8a63-157a-44d4-a1ac-54cc83650b39")]
        public string AD2_PI_Zip
        {
            get { return _AD2_PI_Zip; }
            set { _AD2_PI_Zip = value; }
        }

        string _AD2_PI_UseType;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_UseType.
        /// </summary>
        [TestVariable("efdef5d0-433c-4da2-ba74-930cf3ce118d")]
        public string AD2_PI_UseType
        {
            get { return _AD2_PI_UseType; }
            set { _AD2_PI_UseType = value; }
        }

        string _AD2_PI_PhoneType;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_PhoneType.
        /// </summary>
        [TestVariable("a6bb5d9a-c476-442a-b1d5-269cc0036b21")]
        public string AD2_PI_PhoneType
        {
            get { return _AD2_PI_PhoneType; }
            set { _AD2_PI_PhoneType = value; }
        }

        string _AD2_PI_Source;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_Source.
        /// </summary>
        [TestVariable("a3ac4730-fb77-40c9-8027-b1a7b150487d")]
        public string AD2_PI_Source
        {
            get { return _AD2_PI_Source; }
            set { _AD2_PI_Source = value; }
        }

        string _AD2_PI_PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_PhoneNumber.
        /// </summary>
        [TestVariable("e338a4d4-f8c3-4a27-8f26-08708b9c3356")]
        public string AD2_PI_PhoneNumber
        {
            get { return _AD2_PI_PhoneNumber; }
            set { _AD2_PI_PhoneNumber = value; }
        }

        string _AD2_PI_EmailUseType;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_EmailUseType.
        /// </summary>
        [TestVariable("e174e53b-2c36-4524-b21b-7f13c7637497")]
        public string AD2_PI_EmailUseType
        {
            get { return _AD2_PI_EmailUseType; }
            set { _AD2_PI_EmailUseType = value; }
        }

        string _AD2_PI_EmailSource;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_EmailSource.
        /// </summary>
        [TestVariable("83976115-fb79-4335-8325-d61fd2795207")]
        public string AD2_PI_EmailSource
        {
            get { return _AD2_PI_EmailSource; }
            set { _AD2_PI_EmailSource = value; }
        }

        string _AD2_PI_Email;

        /// <summary>
        /// Gets or sets the value of variable AD2_PI_Email.
        /// </summary>
        [TestVariable("ed3e9ba6-5b49-4b9b-a205-5961e4a6580b")]
        public string AD2_PI_Email
        {
            get { return _AD2_PI_Email; }
            set { _AD2_PI_Email = value; }
        }

        string _Edit_AD2_PI_FirstName;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_FirstName.
        /// </summary>
        [TestVariable("9f417ff5-eff3-426f-898a-c84a9fad1644")]
        public string Edit_AD2_PI_FirstName
        {
            get { return _Edit_AD2_PI_FirstName; }
            set { _Edit_AD2_PI_FirstName = value; }
        }

        string _Edit_AD2_PI_LastName;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_LastName.
        /// </summary>
        [TestVariable("c13193bc-96f2-4f05-b3b7-7e54ec80cc30")]
        public string Edit_AD2_PI_LastName
        {
            get { return _Edit_AD2_PI_LastName; }
            set { _Edit_AD2_PI_LastName = value; }
        }

        string _Edit_AD2_PI_POE;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_POE.
        /// </summary>
        [TestVariable("bb4a4cba-e86c-4e97-a472-f9c57d2a7c67")]
        public string Edit_AD2_PI_POE
        {
            get { return _Edit_AD2_PI_POE; }
            set { _Edit_AD2_PI_POE = value; }
        }

        string _Edit_AD2_PI_Address1;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_Address1.
        /// </summary>
        [TestVariable("f3ab90cf-7a30-43bf-b196-04319fa0e816")]
        public string Edit_AD2_PI_Address1
        {
            get { return _Edit_AD2_PI_Address1; }
            set { _Edit_AD2_PI_Address1 = value; }
        }

        string _Edit_AD2_PI_Address2;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_Address2.
        /// </summary>
        [TestVariable("af0a4279-8998-413c-b058-823ce17452d3")]
        public string Edit_AD2_PI_Address2
        {
            get { return _Edit_AD2_PI_Address2; }
            set { _Edit_AD2_PI_Address2 = value; }
        }

        string _Edit_AD2_PI_City;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_City.
        /// </summary>
        [TestVariable("ee514238-6498-459e-a75b-b19f44660a30")]
        public string Edit_AD2_PI_City
        {
            get { return _Edit_AD2_PI_City; }
            set { _Edit_AD2_PI_City = value; }
        }

        string _Edit_AD2_PI_State;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_State.
        /// </summary>
        [TestVariable("4fc723df-35d7-41f3-a0ac-3f9591719583")]
        public string Edit_AD2_PI_State
        {
            get { return _Edit_AD2_PI_State; }
            set { _Edit_AD2_PI_State = value; }
        }

        string _Edit_AD2_PI_Zip;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_Zip.
        /// </summary>
        [TestVariable("0b2056ae-9eb8-43ad-9bf8-c69e231763b1")]
        public string Edit_AD2_PI_Zip
        {
            get { return _Edit_AD2_PI_Zip; }
            set { _Edit_AD2_PI_Zip = value; }
        }

        string _Edit_AD2_PI_UseType;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_UseType.
        /// </summary>
        [TestVariable("2529a087-e503-42e6-9dfd-57a7f42706df")]
        public string Edit_AD2_PI_UseType
        {
            get { return _Edit_AD2_PI_UseType; }
            set { _Edit_AD2_PI_UseType = value; }
        }

        string _Edit_AD2_PI_PhoneType;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_PhoneType.
        /// </summary>
        [TestVariable("b368f41b-190f-435c-861b-ae95d80fe8eb")]
        public string Edit_AD2_PI_PhoneType
        {
            get { return _Edit_AD2_PI_PhoneType; }
            set { _Edit_AD2_PI_PhoneType = value; }
        }

        string _Edit_AD2_PI_Source;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_Source.
        /// </summary>
        [TestVariable("89f695ad-b7a6-4914-afcb-7d3abeeb7eea")]
        public string Edit_AD2_PI_Source
        {
            get { return _Edit_AD2_PI_Source; }
            set { _Edit_AD2_PI_Source = value; }
        }

        string _Edit_AD2_PI_PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_PhoneNumber.
        /// </summary>
        [TestVariable("8f61f4e8-b59c-43e8-aa93-c1886a959221")]
        public string Edit_AD2_PI_PhoneNumber
        {
            get { return _Edit_AD2_PI_PhoneNumber; }
            set { _Edit_AD2_PI_PhoneNumber = value; }
        }

        string _Edit_AD2_PI_EmailUseType;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_EmailUseType.
        /// </summary>
        [TestVariable("bf61c1aa-0572-4563-9bb3-14d0ae77704a")]
        public string Edit_AD2_PI_EmailUseType
        {
            get { return _Edit_AD2_PI_EmailUseType; }
            set { _Edit_AD2_PI_EmailUseType = value; }
        }

        string _Edit_AD2_PI_EmailSource;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_EmailSource.
        /// </summary>
        [TestVariable("ca8dfccf-80d8-45f9-b099-56f616b3d5d9")]
        public string Edit_AD2_PI_EmailSource
        {
            get { return _Edit_AD2_PI_EmailSource; }
            set { _Edit_AD2_PI_EmailSource = value; }
        }

        string _Edit_AD2_PI_Email;

        /// <summary>
        /// Gets or sets the value of variable Edit_AD2_PI_Email.
        /// </summary>
        [TestVariable("b91c8c1c-e217-4902-840a-42b919663c7f")]
        public string Edit_AD2_PI_Email
        {
            get { return _Edit_AD2_PI_Email; }
            set { _Edit_AD2_PI_Email = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.AD2_PI_FirstName'", repo.ApplicationUnderTest.AD2_PI_FirstNameInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.ApplicationUnderTest.AD2_PI_FirstNameInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_FirstName) on item 'ApplicationUnderTest.AD2_PI_FirstName'.", repo.ApplicationUnderTest.AD2_PI_FirstNameInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_FirstNameInfo, "TagValue", AD2_PI_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_FirstName, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(4));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(5));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AD2_PI_FirstName' with focus on 'ApplicationUnderTest.AD2_PI_FirstName'.", repo.ApplicationUnderTest.AD2_PI_FirstNameInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.AD2_PI_FirstName.PressKeys(Edit_AD2_PI_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_LastName) on item 'ApplicationUnderTest.AD2_PI_LastName'.", repo.ApplicationUnderTest.AD2_PI_LastNameInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_LastNameInfo, "TagValue", AD2_PI_LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_LastName, new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(9));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(10));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AD2_PI_LastName' with focus on 'ApplicationUnderTest.AD2_PI_LastName'.", repo.ApplicationUnderTest.AD2_PI_LastNameInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.AD2_PI_LastName.PressKeys(Edit_AD2_PI_LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_POE) on item 'ApplicationUnderTest.AD2_PI_POE'.", repo.ApplicationUnderTest.AD2_PI_POEInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_POEInfo, "TagValue", AD2_PI_POE);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_POE, new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(14));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(15));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AD2_PI_POE' with focus on 'ApplicationUnderTest.AD2_PI_POE'.", repo.ApplicationUnderTest.AD2_PI_POEInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.AD2_PI_POE.PressKeys(Edit_AD2_PI_POE);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_Address1) on item 'ApplicationUnderTest.AD2_PI_Address1'.", repo.ApplicationUnderTest.AD2_PI_Address1Info, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_Address1Info, "TagValue", AD2_PI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_Address1, new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(19));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(20));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AD2_PI_Address1' with focus on 'ApplicationUnderTest.AD2_PI_Address1'.", repo.ApplicationUnderTest.AD2_PI_Address1Info, new RecordItemIndex(21));
            repo.ApplicationUnderTest.AD2_PI_Address1.PressKeys(Edit_AD2_PI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_Address2) on item 'ApplicationUnderTest.AD2_PI_Address2'.", repo.ApplicationUnderTest.AD2_PI_Address2Info, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_Address2Info, "TagValue", AD2_PI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_Address2, new RecordItemIndex(23));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(24));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(25));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AD2_PI_Address2' with focus on 'ApplicationUnderTest.AD2_PI_Address2'.", repo.ApplicationUnderTest.AD2_PI_Address2Info, new RecordItemIndex(26));
            repo.ApplicationUnderTest.AD2_PI_Address2.PressKeys(Edit_AD2_PI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_City) on item 'ApplicationUnderTest.AD2_PI_City'.", repo.ApplicationUnderTest.AD2_PI_CityInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_CityInfo, "TagValue", AD2_PI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_City, new RecordItemIndex(28));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(29));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(30));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AD2_PI_City' with focus on 'ApplicationUnderTest.AD2_PI_City'.", repo.ApplicationUnderTest.AD2_PI_CityInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.AD2_PI_City.PressKeys(Edit_AD2_PI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_State) on item 'ApplicationUnderTest.AD2_PI_State'.", repo.ApplicationUnderTest.AD2_PI_StateInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_StateInfo, "TagValue", AD2_PI_State);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_State, new RecordItemIndex(33));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(34));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(35));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AD2_PI_State' on item 'ApplicationUnderTest.AD2_PI_State'.", repo.ApplicationUnderTest.AD2_PI_StateInfo, new RecordItemIndex(36));
            repo.ApplicationUnderTest.AD2_PI_State.Element.SetAttributeValue("TagValue", Edit_AD2_PI_State);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(37));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_PI_Zip' and assigning its value to variable 'AD2_PI_Zip'.", repo.ApplicationUnderTest.AD2_PI_ZipInfo, new RecordItemIndex(38));
            AD2_PI_Zip = repo.ApplicationUnderTest.AD2_PI_Zip.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_Zip, new RecordItemIndex(39));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_Zip) on item 'ApplicationUnderTest.AD2_PI_Zip'.", repo.ApplicationUnderTest.AD2_PI_ZipInfo, new RecordItemIndex(40));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_ZipInfo, "TagValue", AD2_PI_Zip);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(41));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(42));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AD2_PI_Zip' with focus on 'ApplicationUnderTest.AD2_PI_Zip'.", repo.ApplicationUnderTest.AD2_PI_ZipInfo, new RecordItemIndex(43));
            repo.ApplicationUnderTest.AD2_PI_Zip.PressKeys(Edit_AD2_PI_Zip);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_PI_UseType' and assigning its value to variable 'AD2_PI_UseType'.", repo.ApplicationUnderTest.AD2_PI_UseTypeInfo, new RecordItemIndex(44));
            AD2_PI_UseType = repo.ApplicationUnderTest.AD2_PI_UseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_UseType, new RecordItemIndex(45));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_UseType) on item 'ApplicationUnderTest.AD2_PI_UseType'.", repo.ApplicationUnderTest.AD2_PI_UseTypeInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_UseTypeInfo, "TagValue", AD2_PI_UseType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(47));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(48));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AD2_PI_UseType' on item 'ApplicationUnderTest.AD2_PI_UseType'.", repo.ApplicationUnderTest.AD2_PI_UseTypeInfo, new RecordItemIndex(49));
            repo.ApplicationUnderTest.AD2_PI_UseType.Element.SetAttributeValue("TagValue", Edit_AD2_PI_UseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_PI_PhoneType' and assigning its value to variable 'AD2_PI_PhoneType'.", repo.ApplicationUnderTest.AD2_PI_PhoneTypeInfo, new RecordItemIndex(50));
            AD2_PI_PhoneType = repo.ApplicationUnderTest.AD2_PI_PhoneType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_PhoneType, new RecordItemIndex(51));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_PhoneType) on item 'ApplicationUnderTest.AD2_PI_PhoneType'.", repo.ApplicationUnderTest.AD2_PI_PhoneTypeInfo, new RecordItemIndex(52));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_PhoneTypeInfo, "TagValue", AD2_PI_PhoneType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(53));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(54));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AD2_PI_PhoneType' on item 'ApplicationUnderTest.AD2_PI_PhoneType'.", repo.ApplicationUnderTest.AD2_PI_PhoneTypeInfo, new RecordItemIndex(55));
            repo.ApplicationUnderTest.AD2_PI_PhoneType.Element.SetAttributeValue("TagValue", Edit_AD2_PI_PhoneType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_PI_Source' and assigning its value to variable 'AD2_PI_Source'.", repo.ApplicationUnderTest.AD2_PI_SourceInfo, new RecordItemIndex(56));
            AD2_PI_Source = repo.ApplicationUnderTest.AD2_PI_Source.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_Source, new RecordItemIndex(57));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_Source) on item 'ApplicationUnderTest.AD2_PI_Source'.", repo.ApplicationUnderTest.AD2_PI_SourceInfo, new RecordItemIndex(58));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_SourceInfo, "TagValue", AD2_PI_Source);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(59));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(60));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AD2_PI_Source' on item 'ApplicationUnderTest.AD2_PI_Source'.", repo.ApplicationUnderTest.AD2_PI_SourceInfo, new RecordItemIndex(61));
            repo.ApplicationUnderTest.AD2_PI_Source.Element.SetAttributeValue("TagValue", Edit_AD2_PI_Source);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_PI_PhoneNumber' and assigning its value to variable 'AD2_PI_PhoneNumber'.", repo.ApplicationUnderTest.AD2_PI_PhoneNumberInfo, new RecordItemIndex(62));
            AD2_PI_PhoneNumber = repo.ApplicationUnderTest.AD2_PI_PhoneNumber.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_PhoneNumber, new RecordItemIndex(63));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_PhoneNumber) on item 'ApplicationUnderTest.AD2_PI_PhoneNumber'.", repo.ApplicationUnderTest.AD2_PI_PhoneNumberInfo, new RecordItemIndex(64));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_PhoneNumberInfo, "TagValue", AD2_PI_PhoneNumber);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(65));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(66));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AD2_PI_PhoneNumber' on item 'ApplicationUnderTest.AD2_PI_PhoneNumber'.", repo.ApplicationUnderTest.AD2_PI_PhoneNumberInfo, new RecordItemIndex(67));
            repo.ApplicationUnderTest.AD2_PI_PhoneNumber.Element.SetAttributeValue("TagValue", Edit_AD2_PI_PhoneNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_PI_EmailUseType' and assigning its value to variable 'AD2_PI_EmailUseType'.", repo.ApplicationUnderTest.AD2_PI_EmailUseTypeInfo, new RecordItemIndex(68));
            AD2_PI_EmailUseType = repo.ApplicationUnderTest.AD2_PI_EmailUseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_EmailUseType, new RecordItemIndex(69));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_EmailUseType) on item 'ApplicationUnderTest.AD2_PI_EmailUseType'.", repo.ApplicationUnderTest.AD2_PI_EmailUseTypeInfo, new RecordItemIndex(70));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_EmailUseTypeInfo, "TagValue", AD2_PI_EmailUseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(71));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press with focus on 'ApplicationUnderTest.AD2_PI_EmailUseType'.", repo.ApplicationUnderTest.AD2_PI_EmailUseTypeInfo, new RecordItemIndex(72));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.AD2_PI_EmailUseType);
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AD2_PI_EmailUseType' on item 'ApplicationUnderTest.AD2_PI_EmailUseType'.", repo.ApplicationUnderTest.AD2_PI_EmailUseTypeInfo, new RecordItemIndex(73));
            repo.ApplicationUnderTest.AD2_PI_EmailUseType.Element.SetAttributeValue("TagValue", Edit_AD2_PI_EmailUseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_PI_EmailSource' and assigning its value to variable 'AD2_PI_EmailSource'.", repo.ApplicationUnderTest.AD2_PI_EmailSourceInfo, new RecordItemIndex(74));
            AD2_PI_EmailSource = repo.ApplicationUnderTest.AD2_PI_EmailSource.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_EmailSource, new RecordItemIndex(75));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_EmailSource) on item 'ApplicationUnderTest.AD2_PI_EmailSource'.", repo.ApplicationUnderTest.AD2_PI_EmailSourceInfo, new RecordItemIndex(76));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_EmailSourceInfo, "TagValue", AD2_PI_EmailSource);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(77));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(78));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Edit_AD2_PI_EmailSource' on item 'ApplicationUnderTest.AD2_PI_EmailSource'.", repo.ApplicationUnderTest.AD2_PI_EmailSourceInfo, new RecordItemIndex(79));
            repo.ApplicationUnderTest.AD2_PI_EmailSource.Element.SetAttributeValue("TagValue", Edit_AD2_PI_EmailSource);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_PI_EmailID' and assigning its value to variable 'AD2_PI_Email'.", repo.ApplicationUnderTest.AD2_PI_EmailIDInfo, new RecordItemIndex(80));
            AD2_PI_Email = repo.ApplicationUnderTest.AD2_PI_EmailID.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_PI_Email, new RecordItemIndex(81));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_PI_Email) on item 'ApplicationUnderTest.AD2_PI_EmailID'.", repo.ApplicationUnderTest.AD2_PI_EmailIDInfo, new RecordItemIndex(82));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_EmailIDInfo, "TagValue", AD2_PI_Email);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(83));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(84));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Edit_AD2_PI_Email' with focus on 'ApplicationUnderTest.AD2_PI_EmailID'.", repo.ApplicationUnderTest.AD2_PI_EmailIDInfo, new RecordItemIndex(85));
            repo.ApplicationUnderTest.AD2_PI_EmailID.PressKeys(Edit_AD2_PI_Email);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Save_Button' at 6;8.", repo.ApplicationUnderTest.Save_ButtonInfo, new RecordItemIndex(86));
            repo.ApplicationUnderTest.Save_Button.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_FirstName) on item 'ApplicationUnderTest.AD2_PI_FirstName'.", repo.ApplicationUnderTest.AD2_PI_FirstNameInfo, new RecordItemIndex(87));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_FirstNameInfo, "TagValue", Edit_AD2_PI_FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_FirstName, new RecordItemIndex(88));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_LastName) on item 'ApplicationUnderTest.AD2_PI_LastName'.", repo.ApplicationUnderTest.AD2_PI_LastNameInfo, new RecordItemIndex(89));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_LastNameInfo, "TagValue", Edit_AD2_PI_LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_LastName, new RecordItemIndex(90));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_Address1) on item 'ApplicationUnderTest.AD2_PI_Address1'.", repo.ApplicationUnderTest.AD2_PI_Address1Info, new RecordItemIndex(91));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_Address1Info, "TagValue", Edit_AD2_PI_Address1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_Address1, new RecordItemIndex(92));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_Address2) on item 'ApplicationUnderTest.AD2_PI_Address2'.", repo.ApplicationUnderTest.AD2_PI_Address2Info, new RecordItemIndex(93));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_Address2Info, "TagValue", Edit_AD2_PI_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_Address2, new RecordItemIndex(94));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_Address2) on item 'ApplicationUnderTest.AD2_PI_City'.", repo.ApplicationUnderTest.AD2_PI_CityInfo, new RecordItemIndex(95));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_CityInfo, "TagValue", Edit_AD2_PI_Address2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_Address2, new RecordItemIndex(96));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_State) on item 'ApplicationUnderTest.AD2_PI_State'.", repo.ApplicationUnderTest.AD2_PI_StateInfo, new RecordItemIndex(97));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_StateInfo, "TagValue", Edit_AD2_PI_State);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_State, new RecordItemIndex(98));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_Zip) on item 'ApplicationUnderTest.AD2_PI_Zip'.", repo.ApplicationUnderTest.AD2_PI_ZipInfo, new RecordItemIndex(99));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_ZipInfo, "TagValue", Edit_AD2_PI_Zip);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_Zip, new RecordItemIndex(100));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_UseType) on item 'ApplicationUnderTest.AD2_PI_UseType'.", repo.ApplicationUnderTest.AD2_PI_UseTypeInfo, new RecordItemIndex(101));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_UseTypeInfo, "TagValue", Edit_AD2_PI_UseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_UseType, new RecordItemIndex(102));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_PhoneType) on item 'ApplicationUnderTest.AD2_PI_PhoneType'.", repo.ApplicationUnderTest.AD2_PI_PhoneTypeInfo, new RecordItemIndex(103));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_PhoneTypeInfo, "TagValue", Edit_AD2_PI_PhoneType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_PhoneType, new RecordItemIndex(104));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_Source) on item 'ApplicationUnderTest.AD2_PI_Source'.", repo.ApplicationUnderTest.AD2_PI_SourceInfo, new RecordItemIndex(105));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_SourceInfo, "TagValue", Edit_AD2_PI_Source);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_Source, new RecordItemIndex(106));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_PhoneNumber) on item 'ApplicationUnderTest.AD2_PI_PhoneNumber'.", repo.ApplicationUnderTest.AD2_PI_PhoneNumberInfo, new RecordItemIndex(107));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_PhoneNumberInfo, "TagValue", Edit_AD2_PI_PhoneNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_PhoneNumber, new RecordItemIndex(108));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_EmailUseType) on item 'ApplicationUnderTest.AD2_PI_EmailUseType'.", repo.ApplicationUnderTest.AD2_PI_EmailUseTypeInfo, new RecordItemIndex(109));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_EmailUseTypeInfo, "TagValue", Edit_AD2_PI_EmailUseType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_EmailUseType, new RecordItemIndex(110));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_Source) on item 'ApplicationUnderTest.AD2_PI_EmailSource'.", repo.ApplicationUnderTest.AD2_PI_EmailSourceInfo, new RecordItemIndex(111));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_EmailSourceInfo, "TagValue", Edit_AD2_PI_Source);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_EmailSource, new RecordItemIndex(112));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_Email) on item 'ApplicationUnderTest.AD2_PI_EmailID'.", repo.ApplicationUnderTest.AD2_PI_EmailIDInfo, new RecordItemIndex(113));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_EmailIDInfo, "TagValue", Edit_AD2_PI_Email);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_Email, new RecordItemIndex(114));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$Edit_AD2_PI_POE) on item 'ApplicationUnderTest.AD2_PI_POE'.", repo.ApplicationUnderTest.AD2_PI_POEInfo, new RecordItemIndex(115));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_PI_POEInfo, "TagValue", Edit_AD2_PI_POE);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", Edit_AD2_PI_POE, new RecordItemIndex(116));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton1' at 46;15.", repo.ApplicationUnderTest.SubmitButton1Info, new RecordItemIndex(117));
            repo.ApplicationUnderTest.SubmitButton1.Click("46;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
