///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Edit_Advesre2_Driver_Attorney_Details recording.
    /// </summary>
    [TestModule("f427f1b6-0b37-4788-ad6f-4f06d4ebbb44", ModuleType.Recording, 1)]
    public partial class Edit_Advesre2_Driver_Attorney_Details : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Edit_Advesre2_Driver_Attorney_Details instance = new Edit_Advesre2_Driver_Attorney_Details();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Edit_Advesre2_Driver_Attorney_Details()
        {
            AD2_AD_Attorney_FirmName = "";
            AD2_AD_Attorney_FirstName = "";
            AD2_AD_Attorney_LastName = "";
            AD2_AD_Attorney_Address1 = "";
            AD2_AD_Attorney_Address2 = "";
            AD2_AD_Attorney_City = "";
            AD2_AD_Attorney_State = "";
            AD2_AD_Attorney_Zip = "";
            AD2_AD_Attorney_Email = "";
            AD2_Attorney_RepDate = "";
            AD2_AD_UseType = "";
            AD2_AD_PhoneType = "";
            AD2_AD_Source = "";
            AD2_AD_PhoneNumber = "";
            AD2_AD_EmailUseType = "";
            AD2_AD_EmailSource = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Edit_Advesre2_Driver_Attorney_Details Instance
        {
            get { return instance; }
        }

#region Variables

        string _AD2_AD_Attorney_FirmName;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_FirmName.
        /// </summary>
        [TestVariable("c96fbd4a-f9ea-49e8-8f42-bb6e87af68e0")]
        public string AD2_AD_Attorney_FirmName
        {
            get { return _AD2_AD_Attorney_FirmName; }
            set { _AD2_AD_Attorney_FirmName = value; }
        }

        string _AD2_AD_Attorney_FirstName;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_FirstName.
        /// </summary>
        [TestVariable("b32c3d31-fa8e-45b3-862c-69f6161cbe53")]
        public string AD2_AD_Attorney_FirstName
        {
            get { return _AD2_AD_Attorney_FirstName; }
            set { _AD2_AD_Attorney_FirstName = value; }
        }

        string _AD2_AD_Attorney_LastName;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_LastName.
        /// </summary>
        [TestVariable("b8ef4d59-3f41-494d-ab9b-4f1445cc1bf0")]
        public string AD2_AD_Attorney_LastName
        {
            get { return _AD2_AD_Attorney_LastName; }
            set { _AD2_AD_Attorney_LastName = value; }
        }

        string _AD2_AD_Attorney_Address1;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_Address1.
        /// </summary>
        [TestVariable("79552169-12d3-40c2-8d00-c82d6da828f3")]
        public string AD2_AD_Attorney_Address1
        {
            get { return _AD2_AD_Attorney_Address1; }
            set { _AD2_AD_Attorney_Address1 = value; }
        }

        string _AD2_AD_Attorney_Address2;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_Address2.
        /// </summary>
        [TestVariable("e4b07dfa-f057-4604-a2f2-dea9f1869595")]
        public string AD2_AD_Attorney_Address2
        {
            get { return _AD2_AD_Attorney_Address2; }
            set { _AD2_AD_Attorney_Address2 = value; }
        }

        string _AD2_AD_Attorney_City;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_City.
        /// </summary>
        [TestVariable("ff17cae4-de40-41e6-937c-61d1f1ac370e")]
        public string AD2_AD_Attorney_City
        {
            get { return _AD2_AD_Attorney_City; }
            set { _AD2_AD_Attorney_City = value; }
        }

        string _AD2_AD_Attorney_State;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_State.
        /// </summary>
        [TestVariable("986e25ea-d4aa-4fe1-ac0b-30a347d6a780")]
        public string AD2_AD_Attorney_State
        {
            get { return _AD2_AD_Attorney_State; }
            set { _AD2_AD_Attorney_State = value; }
        }

        string _AD2_AD_Attorney_Zip;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_Zip.
        /// </summary>
        [TestVariable("50a1b1ae-34c3-4106-8118-1fb968ccb025")]
        public string AD2_AD_Attorney_Zip
        {
            get { return _AD2_AD_Attorney_Zip; }
            set { _AD2_AD_Attorney_Zip = value; }
        }

        string _AD2_AD_Attorney_Email;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Attorney_Email.
        /// </summary>
        [TestVariable("6e9c63b4-2b79-44ea-b789-4133e1a99ae9")]
        public string AD2_AD_Attorney_Email
        {
            get { return _AD2_AD_Attorney_Email; }
            set { _AD2_AD_Attorney_Email = value; }
        }

        string _AD2_Attorney_RepDate;

        /// <summary>
        /// Gets or sets the value of variable AD2_Attorney_RepDate.
        /// </summary>
        [TestVariable("d8d11681-c38c-45cc-b8b3-3c7b9dd8803f")]
        public string AD2_Attorney_RepDate
        {
            get { return _AD2_Attorney_RepDate; }
            set { _AD2_Attorney_RepDate = value; }
        }

        string _AD2_AD_UseType;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_UseType.
        /// </summary>
        [TestVariable("74b29f9b-f201-4b50-9008-53ada5c65a24")]
        public string AD2_AD_UseType
        {
            get { return _AD2_AD_UseType; }
            set { _AD2_AD_UseType = value; }
        }

        string _AD2_AD_PhoneType;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_PhoneType.
        /// </summary>
        [TestVariable("c447179c-eab0-4088-ae05-14e053ae7d7a")]
        public string AD2_AD_PhoneType
        {
            get { return _AD2_AD_PhoneType; }
            set { _AD2_AD_PhoneType = value; }
        }

        string _AD2_AD_Source;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_Source.
        /// </summary>
        [TestVariable("a9667d94-ea3b-4586-8cfa-5dd3db2181ae")]
        public string AD2_AD_Source
        {
            get { return _AD2_AD_Source; }
            set { _AD2_AD_Source = value; }
        }

        string _AD2_AD_PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_PhoneNumber.
        /// </summary>
        [TestVariable("3b6c0924-225b-4d98-af6c-aa58c0310730")]
        public string AD2_AD_PhoneNumber
        {
            get { return _AD2_AD_PhoneNumber; }
            set { _AD2_AD_PhoneNumber = value; }
        }

        string _AD2_AD_EmailUseType;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_EmailUseType.
        /// </summary>
        [TestVariable("7bea4ff7-1852-47e1-93ab-311f15e923b4")]
        public string AD2_AD_EmailUseType
        {
            get { return _AD2_AD_EmailUseType; }
            set { _AD2_AD_EmailUseType = value; }
        }

        string _AD2_AD_EmailSource;

        /// <summary>
        /// Gets or sets the value of variable AD2_AD_EmailSource.
        /// </summary>
        [TestVariable("1161e3da-5284-42c4-b0e8-b0cf2e480dc3")]
        public string AD2_AD_EmailSource
        {
            get { return _AD2_AD_EmailSource; }
            set { _AD2_AD_EmailSource = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Save_Button' at 6;8.", repo.ApplicationUnderTest.Save_ButtonInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Save_Button.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_FirmName' and assigning its value to variable 'AD2_AD_Attorney_FirmName'.", repo.ApplicationUnderTest.AD2_Attorney_FirmNameInfo, new RecordItemIndex(2));
            AD2_AD_Attorney_FirmName = repo.ApplicationUnderTest.AD2_Attorney_FirmName.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_FirmName, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_FirmName) on item 'ApplicationUnderTest.AD2_Attorney_FirmName'.", repo.ApplicationUnderTest.AD2_Attorney_FirmNameInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_FirmNameInfo, "TagValue", AD2_AD_Attorney_FirmName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_FirstName' and assigning its value to variable 'AD2_AD_Attorney_FirstName'.", repo.ApplicationUnderTest.AD2_Attorney_FirstNameInfo, new RecordItemIndex(5));
            AD2_AD_Attorney_FirstName = repo.ApplicationUnderTest.AD2_Attorney_FirstName.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_FirstName, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_FirstName) on item 'ApplicationUnderTest.AD2_Attorney_FirstName'.", repo.ApplicationUnderTest.AD2_Attorney_FirstNameInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_FirstNameInfo, "TagValue", AD2_AD_Attorney_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_LastName' and assigning its value to variable 'AD2_AD_Attorney_LastName'.", repo.ApplicationUnderTest.AD2_Attorney_LastNameInfo, new RecordItemIndex(8));
            AD2_AD_Attorney_LastName = repo.ApplicationUnderTest.AD2_Attorney_LastName.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_LastName, new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_LastName) on item 'ApplicationUnderTest.AD2_Attorney_LastName'.", repo.ApplicationUnderTest.AD2_Attorney_LastNameInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_LastNameInfo, "TagValue", AD2_AD_Attorney_LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_Address1' and assigning its value to variable 'AD2_AD_Attorney_Address1'.", repo.ApplicationUnderTest.AD2_Attorney_Address1Info, new RecordItemIndex(11));
            AD2_AD_Attorney_Address1 = repo.ApplicationUnderTest.AD2_Attorney_Address1.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_Address1, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_Address1) on item 'ApplicationUnderTest.AD2_Attorney_Address1'.", repo.ApplicationUnderTest.AD2_Attorney_Address1Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_Address1Info, "TagValue", AD2_AD_Attorney_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_Address2' and assigning its value to variable 'AD2_AD_Attorney_Address2'.", repo.ApplicationUnderTest.AD2_Attorney_Address2Info, new RecordItemIndex(14));
            AD2_AD_Attorney_Address2 = repo.ApplicationUnderTest.AD2_Attorney_Address2.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_Address2, new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_Address2) on item 'ApplicationUnderTest.AD2_Attorney_Address2'.", repo.ApplicationUnderTest.AD2_Attorney_Address2Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_Address2Info, "TagValue", AD2_AD_Attorney_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_City' and assigning its value to variable 'AD2_AD_Attorney_City'.", repo.ApplicationUnderTest.AD2_Attorney_CityInfo, new RecordItemIndex(17));
            AD2_AD_Attorney_City = repo.ApplicationUnderTest.AD2_Attorney_City.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_City, new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_City) on item 'ApplicationUnderTest.AD2_Attorney_City'.", repo.ApplicationUnderTest.AD2_Attorney_CityInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_CityInfo, "TagValue", AD2_AD_Attorney_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_State' and assigning its value to variable 'AD2_AD_Attorney_State'.", repo.ApplicationUnderTest.AD2_Attorney_StateInfo, new RecordItemIndex(20));
            AD2_AD_Attorney_State = repo.ApplicationUnderTest.AD2_Attorney_State.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_State, new RecordItemIndex(21));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_State) on item 'ApplicationUnderTest.AD2_Attorney_State'.", repo.ApplicationUnderTest.AD2_Attorney_StateInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_StateInfo, "TagValue", AD2_AD_Attorney_State);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_Zip' and assigning its value to variable 'AD2_AD_Attorney_Zip'.", repo.ApplicationUnderTest.AD2_Attorney_ZipInfo, new RecordItemIndex(23));
            AD2_AD_Attorney_Zip = repo.ApplicationUnderTest.AD2_Attorney_Zip.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_Zip, new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_Zip) on item 'ApplicationUnderTest.AD2_Attorney_Zip'.", repo.ApplicationUnderTest.AD2_Attorney_ZipInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_ZipInfo, "TagValue", AD2_AD_Attorney_Zip);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", AD2_AD_Attorney_Zip, repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(26));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_Email' and assigning its value to variable 'AD2_AD_Attorney_Email'.", repo.ApplicationUnderTest.AD2_Attorney_EmailInfo, new RecordItemIndex(27));
            AD2_AD_Attorney_Email = repo.ApplicationUnderTest.AD2_Attorney_Email.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_Email, new RecordItemIndex(28));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_Email) on item 'ApplicationUnderTest.AD2_Attorney_Email'.", repo.ApplicationUnderTest.AD2_Attorney_EmailInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_EmailInfo, "TagValue", AD2_AD_Attorney_Email);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_RepDate' and assigning its value to variable 'AD2_Attorney_RepDate'.", repo.ApplicationUnderTest.AD2_Attorney_RepDateInfo, new RecordItemIndex(30));
            AD2_Attorney_RepDate = repo.ApplicationUnderTest.AD2_Attorney_RepDate.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_Attorney_RepDate, new RecordItemIndex(31));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_Attorney_RepDate) on item 'ApplicationUnderTest.AD2_Attorney_RepDate'.", repo.ApplicationUnderTest.AD2_Attorney_RepDateInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_RepDateInfo, "TagValue", AD2_Attorney_RepDate);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_AD_UseType' and assigning its value to variable 'AD2_AD_UseType'.", repo.ApplicationUnderTest.AD2_AD_UseTypeInfo, new RecordItemIndex(33));
            AD2_AD_UseType = repo.ApplicationUnderTest.AD2_AD_UseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_UseType, new RecordItemIndex(34));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_UseType) on item 'ApplicationUnderTest.AD2_AD_UseType'.", repo.ApplicationUnderTest.AD2_AD_UseTypeInfo, new RecordItemIndex(35));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_AD_UseTypeInfo, "TagValue", AD2_AD_UseType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_AD_PhoneType' and assigning its value to variable 'AD2_AD_PhoneType'.", repo.ApplicationUnderTest.AD2_AD_PhoneTypeInfo, new RecordItemIndex(36));
            AD2_AD_PhoneType = repo.ApplicationUnderTest.AD2_AD_PhoneType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_PhoneType, new RecordItemIndex(37));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_PhoneType) on item 'ApplicationUnderTest.AD2_AD_PhoneType'.", repo.ApplicationUnderTest.AD2_AD_PhoneTypeInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_AD_PhoneTypeInfo, "TagValue", AD2_AD_PhoneType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_AD_Source' and assigning its value to variable 'AD2_AD_Source'.", repo.ApplicationUnderTest.AD2_AD_SourceInfo, new RecordItemIndex(39));
            AD2_AD_Source = repo.ApplicationUnderTest.AD2_AD_Source.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Source, new RecordItemIndex(40));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Source) on item 'ApplicationUnderTest.AD2_AD_Source'.", repo.ApplicationUnderTest.AD2_AD_SourceInfo, new RecordItemIndex(41));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_AD_SourceInfo, "TagValue", AD2_AD_Source);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_AD_PhoneNumber' and assigning its value to variable 'AD2_AD_PhoneNumber'.", repo.ApplicationUnderTest.AD2_AD_PhoneNumberInfo, new RecordItemIndex(42));
            AD2_AD_PhoneNumber = repo.ApplicationUnderTest.AD2_AD_PhoneNumber.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_PhoneNumber, new RecordItemIndex(43));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_PhoneNumber) on item 'ApplicationUnderTest.AD2_AD_PhoneNumber'.", repo.ApplicationUnderTest.AD2_AD_PhoneNumberInfo, new RecordItemIndex(44));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_AD_PhoneNumberInfo, "TagValue", AD2_AD_PhoneNumber);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(45));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton1' at 46;15.", repo.ApplicationUnderTest.SubmitButton1Info, new RecordItemIndex(46));
            //repo.ApplicationUnderTest.SubmitButton1.Click("46;15");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_AD_EmailUseType' and assigning its value to variable 'AD2_AD_EmailUseType'.", repo.ApplicationUnderTest.AD2_AD_EmailUseTypeInfo, new RecordItemIndex(47));
            AD2_AD_EmailUseType = repo.ApplicationUnderTest.AD2_AD_EmailUseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_EmailUseType, new RecordItemIndex(48));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_EmailUseType) on item 'ApplicationUnderTest.AD2_AD_EmailUseType'.", repo.ApplicationUnderTest.AD2_AD_EmailUseTypeInfo, new RecordItemIndex(49));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_AD_EmailUseTypeInfo, "TagValue", AD2_AD_EmailUseType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_AD_EmailSource' and assigning its value to variable 'AD2_AD_EmailSource'.", repo.ApplicationUnderTest.AD2_AD_EmailSourceInfo, new RecordItemIndex(50));
            AD2_AD_EmailSource = repo.ApplicationUnderTest.AD2_AD_EmailSource.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_EmailSource, new RecordItemIndex(51));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_EmailSource) on item 'ApplicationUnderTest.AD2_AD_EmailSource'.", repo.ApplicationUnderTest.AD2_AD_EmailSourceInfo, new RecordItemIndex(52));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_AD_EmailSourceInfo, "TagValue", AD2_AD_EmailSource);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AD2_Attorney_Email' and assigning its value to variable 'AD2_AD_Attorney_Email'.", repo.ApplicationUnderTest.AD2_Attorney_EmailInfo, new RecordItemIndex(53));
            AD2_AD_Attorney_Email = repo.ApplicationUnderTest.AD2_Attorney_Email.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD2_AD_Attorney_Email, new RecordItemIndex(54));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AD2_AD_Attorney_Email) on item 'ApplicationUnderTest.AD2_Attorney_Email'.", repo.ApplicationUnderTest.AD2_Attorney_EmailInfo, new RecordItemIndex(55));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AD2_Attorney_EmailInfo, "TagValue", AD2_AD_Attorney_Email);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(56));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton1' at 46;15.", repo.ApplicationUnderTest.SubmitButton1Info, new RecordItemIndex(57));
            repo.ApplicationUnderTest.SubmitButton1.Click("46;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
